# Metis Final Project Part V: Concatenating all dataframes containing NYT article content into one dataframe that will be used for NLP.

In [1]:
import pickle
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests

### The below code opens the dataframes that were stored in pickle files from previous sections of the project using pickle.load. 

### Further, the head() and .shape functions are called to observe that the dataframe has the correct dimensions and looks aesthetically 'OK'.

In [3]:
text_dfs8_0to1000 = pickle.load( open('text_dfs8_0to1000','rb'))

In [4]:
text_dfs8_0to1000.head(2)

,index,date,url,article,url_date
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...,2001-01-16
1,0,"July 9, 2018",https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec...",2018-07-09

In [5]:
text_dfs8_0to1000.shape

(1000, 5)

In [6]:
text_dfs8_1001to2000 = pickle.load( open('text_dfs8_1001to2000','rb'))

In [7]:
text_dfs8_1001to2000.head(2)

,index,date,url,article,url_date
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...,2001-01-16
1,0,"July 9, 2018",https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec...",2018-07-09

In [8]:
text_dfs8_1001to2000.shape

(1000, 5)

In [9]:
text_dfs8_2001to3000 = pickle.load( open('text_dfs8_2001to3000','rb'))

In [10]:
text_dfs8_2001to3000.head(2)

,index,date,url,article,url_date
0,0,"JULY 10, 2011JULY 10, 2011SEP 5SEP 1AUG 28AUG ...",https://www.nytimes.com/2011/07/11/opinion/11d...,The Republican Party’s strategy in the debt-ce...,2011-07-11
1,0,"JAN. 5, 2009",https://www.nytimes.com/2009/01/06/business/06...,The Securities and Exchange Commission needs t...,2009-01-06

In [11]:
text_dfs8_2001to3000.shape

(999, 5)

In [13]:
text_dfs8_3001to4000 = pickle.load( open('text_dfs8_3001to4000_testing','rb'))

In [14]:
text_dfs8_3001to4000.head(2)

,index,date,url,article,url_date
0,0,"May 2, 2017",https://www.nytimes.com/2017/05/02/business/au...,"For seven years, the steadily expanding auto i...",2017-05-02
1,0,"Feb. 1, 2015",https://www.nytimes.com/2015/02/02/business/ec...,Here are some of the top business stories to p...,2015-02-02

In [15]:
text_dfs8_3001to4000.shape

(999, 5)

In [16]:
text_dfs8_4001to5000_testing = pickle.load( open('text_dfs8_4001to5000_testing','rb'))

In [40]:
text_dfs8_4001to5000_testing.columns = ['index','date', 'url','article']

In [41]:
text_dfs8_4001to5000_testing.head(2)

,index,date,url,article
0,0,"MAY 4, 2009",https://www.nytimes.com/2009/05/05/opinion/05t...,There is something wrong with a system where s...
1,0,,https://www.nytimes.com/2001/11/07/opinion/whi...,Yesterday the Federal Reserve cut interest rat...

In [20]:
text_dfs8_5001to7000_testing = pickle.load( open('text_dfs8_5001to7000_testing','rb'))

In [23]:
print(text_dfs8_5001to7000_testing.shape)
text_dfs8_5001to7000_testing.head(2)

(1999, 4)

,index,date,url,article
0,0,"JUNE 21, 2006",https://www.nytimes.com/2006/06/21/business/21...,Wall Street pared an earlier advance to end mi...
1,0,"Oct. 29, 2014",https://www.nytimes.com/2014/10/30/upshot/the-...,The most important thing to understand about t...

In [24]:
text_dfs8_7001to10000_testing = pickle.load( open('text_dfs8_7001to10000_testing','rb'))

In [25]:
print(text_dfs8_7001to10000_testing.shape)
text_dfs8_7001to10000_testing.head(2)

(2999, 4)

,index,date,url,article
0,0,"NOV. 1, 2006MARCH 9, 2015MARCH 9, 2015",https://www.nytimes.com/2006/11/01/business/01...,"A couple of years ago, Robert E. Rubin — émine..."
1,0,"OCT. 7, 2008",https://www.nytimes.com/2008/10/08/business/08...,DETROIT — The few consumers who are buying new...

In [28]:
text_dfs8_10001to13000_testing = pickle.load( open('text_dfs8_10001to13000_testing','rb'))

In [29]:
print(text_dfs8_10001to13000_testing.shape)
text_dfs8_10001to13000_testing.head(2)

(2999, 4)

,index,date,url,article
0,0,"DEC. 15, 2012AUG 29AUG 19JUL 26JUL 24JUL 15",https://www.nytimes.com/2012/12/16/opinion/sun...,When President-elect Barack Obama selected Tim...
1,0,"OCT. 2, 2011",https://www.nytimes.com/2011/10/03/business/ec...,ECONOMIC REPORTS This week’s data will include...

In [30]:
text_dfs8_13001to14000_testing = pickle.load( open('text_dfs8_13001to14000_testing','rb'))

In [31]:
print(text_dfs8_13001to14000_testing.shape)
text_dfs8_13001to14000_testing.head(2)

(999, 4)

,index,date,url,article
0,0,"JUNE 16, 2013",https://www.nytimes.com/2013/06/17/business/ec...,ECONOMIC REPORTS Data to be released this week...
1,0,"NOV. 23, 2009",https://www.nytimes.com/2009/11/23/us/politics...,President Obama’s scramble for a health care o...

In [32]:
text_dfs8_14001to15000_testing = pickle.load( open('text_dfs8_14001to15000_testing','rb'))

In [33]:
print(text_dfs8_14001to15000_testing.shape)
text_dfs8_14001to15000_testing.head(2)

(999, 4)

,index,date,url,article
0,0,"JAN. 7, 2011",https://www.nytimes.com/2011/01/08/business/ec...,WASHINGTON — President Obama went to a busy wi...
1,0,"November 25, 2012 10:43 pm",https://economix.blogs.nytimes.com/2012/11/25/...,"Every year, the government spends more than $1..."

In [34]:
text_dfs8_15001to16000_testing = pickle.load( open('text_dfs8_15001to16000_testing','rb'))

In [35]:
print(text_dfs8_15001to16000_testing.shape)
text_dfs8_15001to16000_testing.head(2)

(999, 4)

,index,date,url,article
0,0,"March 7, 2013 4:33 pm",https://query.nytimes.com/gst/fullpage.html?re...,9:00 p.m. | UpdatedFour years after the financ...
1,0,"January 28, 2014 11:00 am",https://economix.blogs.nytimes.com/2014/01/28/...,Phillip Swagel is a professor at the School of...

In [36]:
text_dfs8_16001to17000_testing = pickle.load( open('text_dfs8_16001to17000_testing','rb'))

In [37]:
print(text_dfs8_16001to17000_testing.shape)
text_dfs8_16001to17000_testing.head(2)

(998, 4)

,index,date,url,article
0,0,,https://www.nytimes.com/2002/01/12/business/wh...,Wholesale prices in the United States declined...
1,0,"FEB. 7, 2013",https://www.nytimes.com/2013/02/08/business/ec...,WASHINGTON (Reuters) — The number of Americans...

In [38]:
text_dfs8_17001to19702_testing = pickle.load( open('text_dfs8_17001to19702_testing','rb'))

In [39]:
print(text_dfs8_17001to19702_testing.shape)
text_dfs8_17001to19702_testing.head(2)

(2701, 4)

,index,date,url,article
0,0,"June 16, 2011 11:02 am",https://dealbook.nytimes.com/2011/06/16/wall-s...,Wall Street is stepping up its attacks on new ...
1,0,"December 15, 2014 1:03 pm",https://boss.blogs.nytimes.com/2014/12/15/toda...,"Whatâs affecting me, my clients and other sm..."

In [42]:
frames = [text_dfs8_4001to5000_testing,text_dfs8_5001to7000_testing,text_dfs8_7001to10000_testing,text_dfs8_10001to13000_testing,text_dfs8_13001to14000_testing,text_dfs8_14001to15000_testing,text_dfs8_15001to16000_testing,text_dfs8_16001to17000_testing,text_dfs8_17001to19702_testing]

### For the the first part of the NYT_API Scraping, the end results are concatenated using pd.concat(), resulting in a dataframe that contains article content from 15,692 articles. 

### As mentioned in previous sections of the project, this dataframe contains articles that are dated from 2000-2018.

In [43]:
result1 = pd.concat(frames,axis=0)

In [45]:
result1.shape

(15692, 4)

## Extracting Date Fields

### Although the date field for any given article is available to be scraped, I found that it was more efficient to omit any date tags from the scraping. Rather, once the article URL was scraped, I wrote a simple function implementing regex logic to parse this URL and return only the date identified in the URL. 

### Once the date has been extracted, the apply function is used to generate a new column in the dataframe containing the correct date value.

In [46]:
import re, datetime
def regex_date(string):
    try:
        match = re.search('\d{4}/\d{2}/\d{2}',string)
        date = datetime.datetime.strptime(match.group(), '%Y/%m/%d').date()
        return date
    except:
        return None

In [47]:
result1['url_date'] =result1['url'].apply(regex_date)

In [48]:
result1.head(3)

,index,date,url,article,url_date
0,0,"MAY 4, 2009",https://www.nytimes.com/2009/05/05/opinion/05t...,There is something wrong with a system where s...,2009-05-05
1,0,,https://www.nytimes.com/2001/11/07/opinion/whi...,Yesterday the Federal Reserve cut interest rat...,2001-11-07
2,0,"Dec. 4, 2014",https://www.nytimes.com/2014/12/04/opinion/rog...,New York has always been a pretty good baromet...,2014-12-04

In [49]:
frames2 = [text_dfs8_0to1000,text_dfs8_1001to2000,text_dfs8_3001to4000,result1]

In [50]:
result2_part1 =  pd.concat(frames2,axis=0)

In [51]:
result2_part1.head(3)

,index,date,url,article,url_date
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...,2001-01-16
1,0,"July 9, 2018",https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec...",2018-07-09
2,0,"JAN. 22, 2008JAN. 21, 2008JAN. 22, 2008JAN. 22...",https://www.nytimes.com/2008/01/22/business/wo...,"The Federal Reserve, responding to an internat...",2008-01-22

### The resulting dataframe contains 18,691 articles.

In [52]:
result2_part1.shape

(18691, 5)

### The 'date' and 'index' columns are subsequently dropped. Scraping the NYT_API for these article values generated inconsistent results.

In [53]:
columns = ['index','date']
result2_part1.drop(columns, axis=1, inplace=True)

In [54]:
result2_part1.head(2)

,url,article,url_date
0,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...,2001-01-16
1,https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec...",2018-07-09

In [55]:
result2_part1['article'].replace('', np.nan, inplace=True)

In [56]:
result2_part1.shape

(18691, 3)

### Given a cleaner dataframe, nulls are then removed.

In [57]:
result2_part1.dropna(subset=['article'], inplace=True)

In [58]:
result2_part1.shape

(17724, 3)

### The resulting dataframe contains 17,724 rows of article content. The code executed below looks at random samples of the dataframe to ensure that everything looks 'OK'.

In [59]:
result2_part1.sample(50,random_state=42)

,url,article,url_date
2145,https://www.nytimes.com/2004/05/23/business/ev...,"LATELY, even more than usual, the word of the ...",2004-05-23
247,https://www.nytimes.com/2008/09/08/opinion/08k...,"Save the home lenders, save the world? If only...",2008-09-08
1319,https://www.nytimes.com/2017/07/14/business/mu...,"Who are you going to believe, the Fed or your ...",2017-07-14
95,https://www.nytimes.com/2011/10/03/opinion/hol...,The dire state of the world economy reflects d...,2011-10-03
374,https://www.nytimes.com/2003/04/01/business/th...,DOLLAR FALLS. The dollar declined against the ...,2003-04-01
101,https://www.nytimes.com/2002/11/10/magazine/l-...,When I first came across F. Scott Fitzgerald's...,2002-11-10
1575,https://www.nytimes.com/2001/11/12/business/cn...,Think back to the distant past: last year.CNBC...,2001-11-12
29,https://www.nytimes.com/2003/08/29/business/ec...,The economy grew at a revised annual rate of 3...,2003-08-29
314,https://www.nytimes.com/2012/07/12/world/asia/...,WASHINGTON — The White House on Wednesday form...,2012-07-12
248,https://economix.blogs.nytimes.com/2013/01/04/...,"For jobs, the past four years have been a wash...",2013-01-04
2852,https://www.nytimes.com/2008/12/03/business/ec...,"WASHINGTONLast week, on the same day the Treas...",2008-12-03
678,https://www.nytimes.com/2011/10/17/opinion/saf...,WashingtonTHERE’S a lot of talk in Washington ...,2011-10-17
691,https://www.nytimes.com/2003/04/03/business/a-...,"For many economists, the dollar's jagged yearl...",2003-04-03
977,https://dealbook.nytimes.com/2010/03/07/consum...,While much of the Congressional debate over co...,2010-03-07
103,https://www.nytimes.com/2008/10/03/us/03immig....,A report released Thursday by the Pew Hispanic...,2008-10-03
889,https://www.nytimes.com/2012/09/09/your-money/...,"THE unemployment rate is 8.1 percent, hiring h...",2012-09-09
1106,https://www.nytimes.com/2001/03/28/us/bush-say...,President Bush urged lawmakers today not to le...,2001-03-28
147,https://www.nytimes.com/2015/03/31/business/ec...,WASHINGTON — Consumers spent just slightly mor...,2015-03-31
356,https://www.nytimes.com/2011/10/11/opinion/thi...,"The title of the white paper is, admittedly, a...",2011-10-11
2307,https://www.nytimes.com/2008/09/24/business/24...,Congress took on the $700 billion bailout on T...,2008-09-24
2192,https://www.nytimes.com/2008/08/29/business/29...,Wall Street stocks rose Thursday after a bette...,2008-08-29
499,https://www.nytimes.com/2012/09/26/business/ec...,Consumer confidence rose in September to the h...,2012-09-26
232,https://www.nytimes.com/2001/06/28/business/th...,"Blue-chip stocks fell modestly, while technolo...",2001-06-28
2246,https://www.nytimes.com/2006/09/22/us/politics...,"ORLANDO, Fla., Sept. 21 — President Bush began...",2006-09-22
2613,https://www.nytimes.com/2008/12/06/business/ec...,"This article was reported by Louis Uchitelle, ...",2008-12-06
4,https://www.nytimes.com/2006/12/06/opinion/06w...,Talking up the dollar is a tradition among gov...,2006-12-06
1052,https://www.nytimes.com/2001/08/27/opinion/l-t...,To the Editor:Re ''Federal Reserve Cuts Its Ke...,2001-08-27
537,https://www.nytimes.com/2013/05/27/business/ec...,ECONOMIC REPORTS Data to be released include t...,2013-05-27
949,https://www.nytimes.com/2010/05/30/business/30...,THE debt crisis in Europe has already had a si...,2010-05-30
2222,https://www.nytimes.com/2018/02/11/upshot/libe...,"For years, many liberal economists have argued...",2018-02-11
2789,https://www.nytimes.com/2007/06/07/business/06...,"For the second straight day, Wall Street recoi...",2007-06-07
71,https://www.nytimes.com/2009/03/08/opinion/08r...,"“WHEREVER you come near the human race, there’...",2009-03-08
684,https://www.nytimes.com/2011/10/10/business/ec...,ECONOMIC REPORTS Data will include the trade d...,2011-10-10
74,https://www.nytimes.com/2004/06/20/business/ma...,INFLATION and interest rates aren't the only i...,2004-06-20
1184,https://www.nytimes.com/2009/07/15/business/ec...,A recent surge in energy prices helped drive u...,2009-07-15
1814,https://www.nytimes.com/2013/03/08/business/ec...,WASHINGTON (Reuters) — The number of Americans...,2013-03-08
1473,https://www.nytimes.com/2003/07/25/us/quick-bu...,President Bush visited Pennsylvania and Michig...,2003-07-25
1934,https://www.nytimes.com/2015/12/07/opinion/hil...,"SEVEN years ago, the financial crisis sent our...",2015-12-07
670,https://www.nytimes.com/2004/08/08/opinion/l-a...,To the Editor:George P. Shultz repeats the Rep...,2004-08-08
874,https://www.nytimes.com/2012/04/08/your-money/...,THE news from north of the border is both triv...,2012-04-08
1278,https://www.nytimes.com/2003/09/03/us/census-s...,The number of Americans living below the pover...,2003-09-03
116,https://www.nytimes.com/2005/10/16/weekinrevie...,THE United States and Germany are often depict...,2005-10-16
392,https://www.nytimes.com/2002/02/10/business/po...,"STOCKS may be stalled right now, but at least ...",2002-02-10
413,https://boss.blogs.nytimes.com/2013/09/03/in-n...,"At first glance, a new study of the entreprene...",2013-09-03
1765,https://dealbook.nytimes.com/2010/03/18/greens...,In his most detailed examination of the causes...,2010-03-18
364,https://www.nytimes.com/2014/10/11/upshot/a-fa...,The federal budget deficit has narrowed sharpl...,2014-10-11
930,https://www.nytimes.com/2015/10/15/business/de...,Wells Fargo’s superior financial performance h...,2015-10-15
318,https://www.nytimes.com/2009/04/04/world/europ...,PRAGUE — When President Obama arrives here on ...,2009-04-04
590,https://economix.blogs.nytimes.com/2012/09/20/...,"Of all American states, New York again has the...",2012-09-20
50,https://www.nytimes.com/2010/09/12/opinion/12f...,I want to share a couple of articles I recentl...,2010-09-12

In [61]:
result2_part1.dtypes

url         object
article     object
url_date    object
dtype: object

### Having generated a clean dataframe from the first half of the overall articles scraped, the process is then repeated for the second half of the overall articles scraped. These articles date from 1982 to 2000.  

### As shown earlier, the files are opened and examined using the pickle.load() and head() functions.

In [62]:
result2_part2 = pickle.load( open('nyt_result_part2','rb'))

In [63]:
result2_part2.head(4)

,url,article,url_date
0,https://www.nytimes.com/1992/03/07/opinion/for...,"There can hardly be doubt that in the next 6, ...",1992-03-07
1,https://www.nytimes.com/1982/02/22/us/required...,"Attorney General William French Smith, speakin...",1982-02-22
2,https://www.nytimes.com/1984/05/13/us/unions-e...,The American Federation of Labor and Congress ...,1984-05-13
3,https://www.nytimes.com/1996/01/24/business/in...,Personal incomes edged up just two-tenths of 1...,1996-01-24

In [64]:
result2_part2.shape

(10465, 3)

In [65]:
frames3 = [result2_part1,result2_part2]

### The articles from the second half of the scraping are then concatenated to the articles from the first half of the scraping. 

### The resulting dataframe is 28,189 rows long.

In [66]:
complete_df = pd.concat(frames3)

In [67]:
complete_df.shape

(28189, 3)

### The code executed below generates a random sampling of the data to ensure that it looks 'OK'.

In [68]:
complete_df.sample(100,random_state=42)

,url,article,url_date
87,https://www.nytimes.com/2003/02/15/business/in...,Though consumers remain the economy's main eng...,2003-02-15
564,https://www.nytimes.com/1993/01/22/us/upturn-c...,"With the notable exception of California, the ...",1993-01-22
1548,https://www.nytimes.com/2011/06/20/business/ec...,"Two years into a fitful recovery, unemployed A...",2011-06-20
1575,https://www.nytimes.com/1982/06/01/opinion/l-a...,To the Editor:There have been some recent mino...,1982-06-01
659,https://www.nytimes.com/2002/11/17/business/ec...,NOW that the Republicans have regained control...,2002-11-17
1572,https://www.nytimes.com/2015/06/30/business/de...,There are some problems that not even $10 tril...,2015-06-30
1446,https://www.nytimes.com/2018/06/20/business/ec...,The American economy has picked up speed and i...,2018-06-20
734,https://www.nytimes.com/2009/02/09/us/politics...,WASHINGTON — The presidential campaign trail o...,2009-02-09
24,https://www.nytimes.com/2015/03/01/magazine/in...,"The U.S. dollar, as we know it today, was born...",2015-03-01
711,https://www.nytimes.com/2013/05/11/business/ec...,THE recovery from the Great Recession has been...,2013-05-11
1649,https://www.nytimes.com/1986/10/06/business/pu...,The economy expanded slightly in September and...,1986-10-06
341,https://www.nytimes.com/2014/02/14/business/ec...,WASHINGTON — Retail sales unexpectedly fell la...,2014-02-14
967,https://www.nytimes.com/2008/01/16/business/16...,"Ben Bernanke, meet Gary Crittenden. While you’...",2008-01-16
757,https://www.nytimes.com/1991/12/22/opinion/in-...,Mario Cuomo warned the nation that he would no...,1991-12-22
2972,https://www.nytimes.com/2001/09/18/business/in...,Inventories of unsold goods at United States c...,2001-09-18
173,https://www.nytimes.com/1984/12/08/business/bo...,"Bond prices fell sharply yesterday, with all o...",1984-12-08
254,https://economix.blogs.nytimes.com/2011/07/08/...,The main problem with the job market is the la...,2011-07-08
699,https://query.nytimes.com/gst/fullpage.html?re...,"To the Editor:Re ""You're Rich? Terrific. Now P...",None
1133,https://www.nytimes.com/2008/03/23/opinion/23k...,The Iraq war is now going better than expected...,2008-03-23
789,https://www.nytimes.com/2012/11/07/opinion/aft...,"THE voters have spoken. So, what now? How will...",2012-11-07
590,https://www.nytimes.com/2002/11/10/magazine/l-...,"Thank you, thank you, Paul Krugman, for finall...",2002-11-10
1218,https://www.nytimes.com/1982/08/18/business/ho...,"For the past two years, interest rates have be...",1982-08-18
446,https://www.nytimes.com/2001/11/15/business/re...,"Retail sales surged 7.1 percent in October, al...",2001-11-15
2640,https://www.nytimes.com/2010/11/16/business/ec...,A weakening currency traditionally helps a cou...,2010-11-16
1364,https://www.nytimes.com/2008/01/13/business/13...,It was another dismal week for the stock marke...,2008-01-13
8,https://www.nytimes.com/1983/01/11/business/ma...,THE stock market continued to confound its dou...,1983-01-11
12,https://www.nytimes.com/1987/05/16/us/producer...,More evidence of stepped-up inflation emerged ...,1987-05-16
1681,https://www.nytimes.com/1994/08/11/business/bu...,CompaniesSome brokerage firms have found ways ...,1994-08-11
830,https://www.nytimes.com/1987/06/17/business/fa...,"Output at the nation's factories, mines and ut...",1987-06-17
1032,https://www.nytimes.com/1992/05/30/business/co...,Benefiting from severe cost-cutting and modera...,1992-05-30
...,...,...,...
1693,https://www.nytimes.com/1991/03/24/business/lo...,MONDAY: Existing home sales for February. * Au...,1991-03-24
286,https://www.nytimes.com/2010/02/21/opinion/21f...,"A small news item from Tracy, Calif., caught m...",2010-02-21
777,https://www.nytimes.com/2006/04/29/business/29...,GRIM news about energy prices collided with gr...,2006-04-29
703,https://www.nytimes.com/2009/11/17/business/ec...,Retail sales in the United States increased by...,2009-11-17
627,https://www.nytimes.com/1998/10/18/opinion/l-i...,To the Editor:I don't feel sorry for Wendy Wil...,1998-10-18
524,https://www.nytimes.com/2003/08/18/opinion/l-c...,"To the Editor:Paul Krugman (column, Aug. 15) d...",2003-08-18
2282,https://www.nytimes.com/2018/03/28/opinion/tru...,The many Americans now cheering President Trum...,2018-03-28
179,https://www.nytimes.com/2014/08/06/upshot/luck...,"Though I typically resist, my wife often tries...",2014-08-06
422,https://www.nytimes.com/2012/12/04/business/ec...,WASHINGTON (AP) — American manufacturing decli...,2012-12-04
2314,https://www.nytimes.com/2009/02/20/travel/esca...,"ONCE again, people are talking about Bretton W...",2009-02-20
802,https://www.nytimes.com/1986/09/19/business/gn...,The nation's economy grew a mere six-tenths of...,1986-09-19
523,https://boss.blogs.nytimes.com/2014/03/06/toda...,"Whatâs affecting me, my clients and other sm...",2014-03-06
2317,https://economix.blogs.nytimes.com/2013/10/02/...,Could the government shutdown now under way ac...,2013-10-02
304,https://www.nytimes.com/1984/09/22/us/briefing...,"The French Finance Minister,Pierre Beregovoy, ...",1984-09-22
1239,https://www.nytimes.com/2013/11/09/business/ec...,Consumer sentiment unexpectedly dipped in Nove...,2013-11-09
216,https://www.nytimes.com/1997/05/10/business/le...,In nearly 10 years as chairman of the Federal ...,1997-05-10
1584,https://www.nytimes.com/1983/02/22/business/us...,A top Energy Department official told a Congre...,1983-02-22
1987,https://www.nytimes.com/1986/06/22/weekinrevie...,WHEN Middle Western governors met here last we...,1986-06-22
386,https://economix.blogs.nytimes.com/2010/08/12/...,Simon Johnson and James Kwak are the authors o...,2010-08-12
1122,https://www.nytimes.com/2012/10/23/us/across-c...,"EAGLE GROVE, Iowa — After initially trickling ...",2012-10-23
836,https://www.nytimes.com/1985/12/08/business/we...,In suspending General Dynamics from obtaining ...,1985-12-08
760,https://www.nytimes.com/2003/08/14/us/kentucky...,"Improbable as it sounds, the first major test ...",2003-08-14
218,https://www.nytimes.com/2012/11/03/us/politics...,WASHINGTON — What would a President Romney hav...,2012-11-03
2011,https://www.nytimes.com/2009/04/04/business/ec...,"With 663,000 more jobs disappearing from the A...",2009-04-04
156,https://www.nytimes.com/2012/09/22/business/ec...,"A YEAR ago, when the United States government ...",2012-09-22
978,https://www.nytimes.com/2009/03/11/opinion/11w...,"In tough times, there is a strong temptation t...",2009-03-11
1441,https://www.nytimes.com/2005/05/20/opinion/20k...,Stories about the new Treasury report condemni...,2005-05-20
1276,https://www.nytimes.com/1983/03/06/realestate/...,Conventional mortgages have fixed rates and te...,1983-03-06
459,https://www.nytimes.com/1990/04/22/business/bu...,COMPANIESMilken Settlement ReportedThe Milken ...,1990-04-22
294,https://www.nytimes.com/2004/06/04/opinion/l-t...,"To the Editor:David Brooks (column, June 1) ma...",2004-06-04

### Using the isnull function, we can observe that joining the two dataframes resulted in 231 null values. Those values are subsequently dropped using the dropna() function.

In [69]:
complete_df.isnull().values.sum()

231

In [71]:
complete_df.dropna(inplace=True)

In [72]:
complete_df.shape

(27958, 3)

### The resulting dataframe contains 27,958 rows of article content spanning 1982 to 2018. The dataframe is then sampled to make sure everything looks OK. 

### The file is then stored as a pickle file.

In [75]:
complete_df.sample(200,random_state=420)

,url,article,url_date
377,https://www.nytimes.com/2011/03/26/business/ec...,The nation’s economy grew at a 3.1 percent ann...,2011-03-26
390,https://www.nytimes.com/2018/06/01/business/ec...,Friday’s jobs report was a blockbuster: Job gr...,2018-06-01
590,https://www.nytimes.com/1988/11/06/business/da...,THE ECONOMY,1988-11-06
920,https://www.nytimes.com/2015/12/05/business/ec...,Consider it a done deal.American employers exp...,2015-12-05
910,https://dealbook.nytimes.com/2014/04/29/big-te...,"Updated, 8:49 p.m. | It has long been the $45 ...",2014-04-29
1994,https://www.nytimes.com/1982/06/04/nyregion/qu...,"''We in the West have big problems, and we mus...",1982-06-04
1158,https://www.nytimes.com/1982/08/22/nyregion/30...,New York City teen-agers continued to fare bad...,1982-08-22
112,https://www.nytimes.com/1991/10/18/business/bi...,In an inflation report that many investors and...,1991-10-18
287,https://www.nytimes.com/2010/09/15/realestate/...,"When Kenny Horowitz, a longtime worker in the ...",2010-09-15
314,https://www.nytimes.com/2012/07/12/world/asia/...,WASHINGTON — The White House on Wednesday form...,2012-07-12
117,https://www.nytimes.com/2008/01/31/opinion/31e...,ChicagoTHE House of Representatives passed a b...,2008-01-31
1833,https://www.nytimes.com/2011/09/27/opinion/bro...,"If you want a big swig of despair, listen to t...",2011-09-27
516,https://www.nytimes.com/2011/10/19/arts/music/...,"“Every successful movement has a soundtrack,” ...",2011-10-19
551,https://www.nytimes.com/2011/05/14/opinion/l14...,To the Editor:Re “Critics Fear G.O.P.’s Propos...,2011-05-14
1308,https://www.nytimes.com/2007/01/05/business/05...,Wall Street struggled but ultimately closed hi...,2007-01-05
13,https://www.nytimes.com/2013/03/02/business/ec...,Busier factories and growing optimism among co...,2013-03-02
2517,https://www.nytimes.com/2001/04/28/business/ec...,The economy showed surprising resilience in th...,2001-04-28
2723,https://www.nytimes.com/1991/12/25/business/ac...,"For all the talk of a ""white collar"" recession...",1991-12-25
19,https://www.nytimes.com/2009/05/23/business/ec...,"FOR many years, unemployment in the United Sta...",2009-05-23
2440,https://www.nytimes.com/1992/07/11/us/the-1992...,Ross Perot brushed aside questions today about...,1992-07-11
2061,https://www.nytimes.com/2009/05/06/business/ec...,"WASHINGTON — Ben S. Bernanke, the chairman of ...",2009-05-06
296,https://economix.blogs.nytimes.com/2011/03/03/...,"In one of our recent Book Chats, Tyler Cowen o...",2011-03-03
288,https://www.nytimes.com/1993/02/14/business/ma...,AS details leak out regarding President Clinto...,1993-02-14
1306,https://www.nytimes.com/2012/03/30/business/da...,Stocks rallied to finish mixed Thursday after ...,2012-03-30
582,https://www.nytimes.com/1985/08/05/business/pu...,The nation's industrial economy continued to s...,1985-08-05
316,https://www.nytimes.com/1995/02/25/business/us...,Prices of Treasury securities were mixed yeste...,1995-02-25
807,https://www.nytimes.com/2001/07/14/business/us...,New evidence of a weak economy appeared yester...,2001-07-14
674,https://www.nytimes.com/1982/11/14/weekinrevie...,"At first, the daily private Presidential sessi...",1982-11-14
1379,https://www.nytimes.com/1982/11/03/business/ec...,THE philosopher Mortimer Adler has been explai...,1982-11-03
6,https://www.nytimes.com/1999/11/17/business/sh...,The Federal Reserve raised interest rates by a...,1999-11-17
...,...,...,...
2001,https://www.nytimes.com/2008/12/14/magazine/14...,Among the most astonishing statements to be ma...,2008-12-14
787,https://www.nytimes.com/2011/12/24/opinion/noc...,So this is how the Big Lie works.You begin wit...,2011-12-24
1035,https://www.nytimes.com/1998/08/10/business/be...,"Max G. Rodel, a 55-year-old chemist and invest...",1998-08-10
632,https://www.nytimes.com/1982/08/13/opinion/in-...,"If President Reagan barnstorms the West, then ...",1982-08-13
1976,https://www.nytimes.com/2001/02/14/business/th...,Stock prices moved lower yesterday after Alan ...,2001-02-14
1148,https://www.nytimes.com/2008/12/18/business/wo...,FRANKFURT — The dollar is sliding back into ...,2008-12-18
182,https://www.nytimes.com/1996/01/28/us/gramm-br...,Senator Phil Gramm came here this morning for ...,1996-01-28
429,https://www.nytimes.com/2009/03/22/education/2...,"RANDOLPH, Utah — Dale Lamborn, the superintend...",2009-03-22
895,https://www.nytimes.com/1992/12/30/opinion/l-c...,"To the Editor:You report that Robert Reich, Pr...",1992-12-30
689,https://www.nytimes.com/1992/01/16/us/1992-cam...,After roaming far and wide and enjoying many f...,1992-01-16
616,https://www.nytimes.com/2014/06/04/business/ec...,Factory orders rose for a third consecutive mo...,2014-06-04
1542,https://www.nytimes.com/1994/04/06/opinion/wal...,The Dow Jones Industrial stock average soared ...,1994-04-06
633,https://www.nytimes.com/1983/01/20/business/st...,Following is the text of a letter addressed to...,1983-01-20
2109,https://www.nytimes.com/2008/09/15/business/15...,"This article was reported by Jenny Anderson, E...",2008-09-15
893,https://www.nytimes.com/2008/10/12/weekinrevie...,"AT the turn of the 20th century, toward the en...",2008-10-12
410,https://www.nytimes.com/1988/08/13/us/call-to-...,"Vice President Bush, admitting that his campai...",1988-08-13
2830,https://www.nytimes.com/2005/10/14/business/14...,"The nation's trade deficit worsened in August,...",2005-10-14
1372,https://dealbook.nytimes.com/2010/04/13/dear-p...,"Dear Professor Krugman,I read your blog post a...",2010-04-13
1193,https://www.nytimes.com/1989/11/19/business/bu...,"In 1971, following President Nixon's repudiati...",1989-11-19
743,https://economix.blogs.nytimes.com/2010/08/03/...,The economy most likely grew much less in the ...,2010-08-03
595,https://www.nytimes.com/2008/03/10/opinion/10k...,Friday’s employment report — which was so wea...,2008-03-10
2658,https://www.nytimes.com/2007/06/02/business/02...,WHAT happens when the American housing industr...,2007-06-02
1509,https://www.nytimes.com/1983/11/20/business/ra...,the price of money - so dominate the investmen...,1983-11-20
1253,https://economix.blogs.nytimes.com/2013/10/11/...,"It’s no longer the economy, stupid — it’s the ...",2013-10-11
222,https://www.nytimes.com/1986/10/01/business/pr...,President Reagan said today he wants American ...,1986-10-01
4,https://www.nytimes.com/1985/07/08/business/ma...,ALTHOUGH railroad traffic has been disappointi...,1985-07-08
232,https://www.nytimes.com/2009/10/08/us/politics...,WASHINGTON — Democratic Congressional leaders ...,2009-10-08
1523,https://www.nytimes.com/2004/06/13/business/su...,"INVESTMENT advisers have been warning, to litt...",2004-06-13
1320,https://www.nytimes.com/2000/10/19/us/2000-cam...,Sensing that Vice President Al Gore's debate p...,2000-10-19
1110,https://www.nytimes.com/2000/02/23/opinion/l-e...,"To the Editor:Paul Krugman (column, Feb. 20) f...",2000-02-23

In [76]:
pickle.dump(complete_df, open( "complete_df_nyt_kojak", "wb" ) )