# Metis Final Project Part III. Using Beautiful Soup to scrape article text-content and store the content in a Pandas dataframe.

In [1]:
import pickle
import pandas as pd
import numpy as np
from bs4 import BeautifulSoup
import requests
doc = pickle.load( open('completelist.pickle','rb'))
url_list = list(doc)

In [2]:
len(url_list)

19702

In [4]:
url_list0to1000 = url_list[0:1000]

In [5]:
len(url_list0to1000)

1000

### The below code writes a function to scrape NYT article URLs for text and date content. The article tags identified for both types of content were determined through a trial and error process searching through articles from different sections (i.e. Business, Economics, DealBook, etc.). The data is then appended to a blank dataframe.

df = pd.DataFrame()

def get_text1(url):
    
    stringone = ''
    content_string2 = ''
    content_string4 = ''
    string_date2 = ''
    string_date3 = ''
    page = requests.get(url).text
    soup = BeautifulSoup(page, "lxml")
    #url2 = pd.Series(url)
        
    article_content = soup.find_all('p', attrs={'class' : 'story-body-text story-content'})
        #print(article_content[0])
        #print(len(article_content))

    for i in article_content:
        stringone += i.text.strip()
    #print(stringone)
    article = pd.Series(stringone)

    if stringone == '':

        article_content1 = soup.find_all('p', attrs={'class' : 'css-1i0edl6 e2kc3sl0'})

        #string2 = '' ... moved to the top
        for i in article_content1:
            content_string2 += (i.text.strip())
        article = pd.Series(content_string2)

        if content_string2 == '':


            article_content_4 = soup.find_all('p', attrs={'class' : 'story-body-text'})
            #string4 = ''
            for i in article_content_4:
                content_string4 += (i.text.strip())
            article = pd.Series(content_string4)

                        
              
    date2 = soup.find_all('time', attrs={'class' : 'dateline'})
    #string_date2 = ''
    for i in date2:
        string_date2 += i.text.strip()
    df_date = pd.Series(string_date2) #to be appended to dataframe lower down

    if string_date2 == '':


        date3 = soup.find_all('time', attrs={'class' : 'css-pnci9c eqgapgq0'})
        #string_date3 = ''
        for i in date3:
            string_date3 += i.text.strip()
        df_date = pd.Series(string_date3)

        #if string_date3 == '':
            #masthead = soup.find_all(class_='sharetools theme-classic sharetools-masthead ')
            #a = str(masthead[0])
            #a = a.split("=")
            #a = [v.split("\" ")[0][1:] for v in a]
            #df_date = pd.Series(a[6])
                        
    
    url2 = pd.Series(url) ##these are to be appended to dataframe lower down
    frames = [df_date,url2,article] #authorz,#descrip,
    result = pd.concat(frames,axis=1)
    
    return(result)

In [8]:
url_test = 'https://www.nytimes.com/2001/01/16/nyregion/c-corrections-459399.html'

In [10]:
text_dfs = [get_text1(url) for url in url_list0to1000]

In [12]:
text_dfs3 = pd.concat(text_dfs).reset_index()

In [13]:
text_dfs3.shape

(1000, 4)

In [14]:
text_dfs3

,index,0,1,2
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...
1,0,"July 9, 2018",https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec..."
2,0,"JAN. 22, 2008JAN. 21, 2008JAN. 22, 2008JAN. 22...",https://www.nytimes.com/2008/01/22/business/wo...,"The Federal Reserve, responding to an internat..."
3,0,"August 25, 2015August 25, 2015 7:28 am",https://news.blogs.nytimes.com/2015/08/25/morn...,CHINA CUTS RATES AFTER SHANGHAI STOCKS PLUNGE ...
4,0,"DEC. 8, 2010",https://www.nytimes.com/2010/12/09/opinion/09t...,There are compelling reasons why Congress shou...
5,0,"June 29, 2018",https://www.nytimes.com/2018/06/29/us/politics...,"— Larry Kudlow, the White House economic advi..."
6,0,,https://www.nytimes.com/2003/06/10/business/fo...,By signaling that he is prepared to cut intere...
7,0,,https://www.nytimes.com/2000/11/05/weekinrevie...,A chart last Sunday illustrating definitions o...
8,0,"Sept. 15, 2015",https://www.nytimes.com/2015/09/16/business/ec...,WASHINGTON — Data released on Tuesday revealed...
9,0,"Nov. 15, 2016",https://www.nytimes.com/2016/11/16/business/ec...,The harvest had just begun when agents from th...
10,0,,https://www.nytimes.com/video/world/1194832824...,
11,0,,https://www.nytimes.com/2001/02/09/us/happily-...,"During the presidential campaign, Al Gore port..."
12,0,"APRIL 25, 2010",https://www.nytimes.com/2010/04/26/business/26...,ECONOMIC REPORTS Data will include the Standa...
13,0,"APRIL 28, 2011SEP 3AUG 31AUG 30AUG 27AUG 26",https://www.nytimes.com/2011/04/29/opinion/29k...,Last month more than 14 million Americans were...
14,0,"JUNE 27, 2011AUG 31AUG 24AUG 10AUG 3JUL 27",https://www.nytimes.com/2011/06/28/opinion/28i...,NEW YORK — The philosopher Isaiah Berlin once ...
15,0,,https://www.nytimes.com/video/us/politics/1247...,
16,0,"DEC. 15, 2008DEC. 9, 2008DEC. 9, 2008",https://www.nytimes.com/2008/12/16/opinion/lwe...,To the Editor:Re “Where Are the New Jobs for W...
17,0,"JUNE 22, 2011JUNE 22, 2011JUNE 22, 2011, 9:24 ...",https://www.nytimes.com/2011/06/23/business/ec...,"WASHINGTON — And at the end of June, the Feder..."
18,0,,https://www.nytimes.com/video/multimedia/12480...,
19,0,"MAY 22, 2009FEB. 17, 2015FEB. 17, 2015",https://www.nytimes.com/2009/05/23/business/ec...,"FOR many years, unemployment in the United Sta..."
20,0,"MAY 19, 2010",https://www.nytimes.com/2010/05/20/business/20...,WASHINGTON — The Federal Reserve indicated tha...
21,0,,https://www.nytimes.com/2004/01/08/business/ec...,"''THIS administration today, here and now, dec..."
22,0,"OCT. 10, 2008",https://www.nytimes.com/2008/10/11/us/politics...,Senator John McCain proposed on Friday that in...
23,0,"July 23, 2012 7:00 am",https://boss.blogs.nytimes.com/2012/07/23/this...,DashboardA daily roundup of small-business dev...
24,0,"DEC. 6, 2006",https://www.nytimes.com/2006/12/06/business/06...,A revised Labor Department report on worker pr...
25,0,"OCT. 19, 2008FEB. 22, 2015OCT. 17, 2008FEB. 22...",https://www.nytimes.com/2008/10/20/business/20...,Fear is running high on Wall Street. Just look...
26,0,"April 2, 2009 12:00 am",https://learning.blogs.nytimes.com/2009/04/02/...,Note: This lesson was originally published on ...
27,0,"JUNE 21, 2011MAY 29MAY 22MAY 15MAY 8MAY 1",https://www.nytimes.com/2011/06/22/business/ec...,Republicans say they won’t raise taxes. Democr...
28,0,,https://www.nytimes.com/2006/01/07/politics/07...,"WASHINGTON, Jan. 6 - The United States generat..."
29,0,"May 28, 2015",https://www.nytimes.com/2015/05/29/business/ec...,WASHINGTON — Americans signed contracts to buy...
...,...,...,...,...
970,0,"OCT. 16, 2008",https://www.nytimes.com/2008/10/16/opinion/16c...,"In our interconnected world, the American fina..."
971,0,"SEPT. 5, 2012MAY 24, 2011MAY 24, 2011",https://www.nytimes.com/2012/09/06/us/like-the...,WASHINGTON — From Uncle Sam saying “I want YOU...
972,0,"NOV. 17, 2010",https://www.nytimes.com/2010/11/18/business/18...,Stocks were little changed on Wednesday as con...
973,0,,https://www.nytimes.com/2001/12/21/us/gop-push...,When President Bush's push for an economic sti...
974,0,,https://www.nytimes.com/2002/12/08/weekinrevie...,IF you measure the success of a president by j...
975,0,"FEB. 22, 2013FEB. 22, 2013AUG 29AUG 26AUG 23AU...",https://www.nytimes.com/2013/02/23/opinion/blo...,"It’s crunch time.The sequester’s automatic, ac..."
976,0,,https://www.nytimes.com/2003/03/30/business/ec...,"RIGHT now, the war in Iraq is the most importa..."
977,0,"May 18, 2016May 18, 2016 6:27 am",https://news.blogs.nytimes.com/2016/05/18/morn...,A TALE OF TWO SILICON VALLEYS | Lending Club...
978,0,"OCT. 25, 2011OCT. 25, 2011OCT. 25, 2011OCT. 25...",https://www.nytimes.com/2011/10/26/us/politics...,"With Election Day just over a year away, a dee..."
979,0,"January 14, 2015 8:30 am",https://dealbook.nytimes.com/2015/01/14/wells-...,Many people doubt the strength of the United S...
980,0,"January 14, 2010 8:27 pm",https://dealbook.nytimes.com/2010/01/14/the-st...,"From Eric Dash, a DealBook colleague:The idea ..."
981,0,"AUG. 20, 2007",https://www.nytimes.com/2007/08/20/business/20...,EYE ON THE ECONOMY Wall Street will be looking...
982,0,"OCT. 16, 2008OCT. 16, 2008OCT. 16, 2008OCT. 16...",https://www.nytimes.com/2008/10/16/opinion/16b...,DublinIN the ravening years of the Celtic Tige...
983,0,,https://www.nytimes.com/video/business/economy...,
984,0,"JUNE 25, 2009JULY 29, 2013JULY 22, 2009JULY 21...",https://www.nytimes.com/2009/06/26/business/26...,WASHINGTON — It has become the trillion-dollar...
985,0,,https://www.nytimes.com/2018/06/05/pageoneplus...,FRONT PAGEAn article on May 30 about the eques...
986,0,"MAY 1, 2009",https://www.nytimes.com/2009/05/02/opinion/02h...,The incredibly clueless stewards of the incred...
987,0,"OCT. 2, 2010SEPT. 25, 2010SEPT. 25, 2010",https://www.nytimes.com/2010/10/03/business/03...,To the Editor:In “What the Rich Don’t Need” (E...
988,0,"FEB. 25, 2006",https://www.nytimes.com/2006/02/25/business/wo...,"Correction AppendedHOUSTON, Feb. 24 - Despite ..."
989,0,,https://www.nytimes.com/2014/07/04/business/jo...,
990,0,"JULY 28, 2005",https://www.nytimes.com/2005/07/28/business/wo...,"WASHINGTON, Thursday, July 28 - The House of R..."
991,0,,https://www.nytimes.com/2000/06/15/business/re...,"The national inflation rate, which has been in..."
992,0,,https://www.nytimes.com/video/business/economy...,
993,0,,https://www.nytimes.com/2004/08/11/business/fe...,The Federal Reserve increased short-term inter...
994,0,"April 14, 2010 1:52 pm",https://dealbook.nytimes.com/2010/04/14/obama-...,In the face of stiff opposition from Senate Re...
995,0,"May 17, 2017",https://www.nytimes.com/2017/05/17/business/de...,"It took nearly a decade, but debt has made a c..."
996,0,"APRIL 9, 2009",https://www.nytimes.com/2009/04/10/business/10...,"Only a year ago, all the stars appeared to be ..."
997,0,"APRIL 20, 2008FEB. 24, 2015FEB. 24, 2015",https://www.nytimes.com/2008/04/20/magazine/20...,A CLEAR SENSE OF EMISSION: Carbon-dioxide equi...
998,0,,https://www.nytimes.com/2002/11/19/business/wh...,These are gloomy times for those who plead for...
999,0,"SEPT. 5, 4800",https://www.nytimes.com/2001/11/11/business/pe...,Perhaps people are following President Bush's ...

In [15]:
text_dfs3.columns = ['index','date', 'url','article']

In [16]:
text_dfs3.head(1)

,index,date,url,article
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...

In [17]:
text_dfs8 = text_dfs3

### The below code removes na' values from the data frames and checks to ensure that the code worked properly. The code then proceeds to the regex_date function, which parses through the 'url' column in the pandas data frame to access the date in a clean fashion. The results from the scraper did not generate sensible date content, thus this alternative method was employed.

In [18]:
text_dfs8 = text_dfs8.dropna(subset = ['url','article'])

In [19]:
text_dfs8.isnull().values.sum()

0

In [20]:
import re, datetime
def regex_date(string):
    try:
        match = re.search('\d{4}/\d{2}/\d{2}',string)
        date = datetime.datetime.strptime(match.group(), '%Y/%m/%d').date()
        return date
    except:
        return None

In [21]:
text_dfs8['url_date'] = text_dfs8['url'].apply(regex_date)

In [22]:
text_dfs8.head()

,index,date,url,article,url_date
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...,2001-01-16
1,0,"July 9, 2018",https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec...",2018-07-09
2,0,"JAN. 22, 2008JAN. 21, 2008JAN. 22, 2008JAN. 22...",https://www.nytimes.com/2008/01/22/business/wo...,"The Federal Reserve, responding to an internat...",2008-01-22
3,0,"August 25, 2015August 25, 2015 7:28 am",https://news.blogs.nytimes.com/2015/08/25/morn...,CHINA CUTS RATES AFTER SHANGHAI STOCKS PLUNGE ...,2015-08-25
4,0,"DEC. 8, 2010",https://www.nytimes.com/2010/12/09/opinion/09t...,There are compelling reasons why Congress shou...,2010-12-09

In [23]:
text_dfs8.shape

(1000, 5)

In [24]:
text_dfs8.dtypes

index        int64
date        object
url         object
article     object
url_date    object
dtype: object

In [25]:
pickle.dump( text_dfs8, open( "text_dfs8_0to1000", "wb" ) )

In [28]:
text_dfs8_0to1000 = text_dfs8

In [30]:
url_list1001to2000 = url_list[1001:2000]

### The below code creates the same data frame tables for sections of every 1000 articles in the first list (date range 2000-2018). The dataframes are stored in pickle files as well.

In [31]:
text_dfs8_1001to2000 = [get_text1(url) for url in url_list1001to2000]

In [32]:
text_dfs8_1001to2000 = pd.concat(text_dfs).reset_index()

In [33]:
text_dfs8_1001to2000.shape

(1000, 4)

In [34]:
text_dfs8_1001to2000.head(10)

,index,0,1,2
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...
1,0,"July 9, 2018",https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec..."
2,0,"JAN. 22, 2008JAN. 21, 2008JAN. 22, 2008JAN. 22...",https://www.nytimes.com/2008/01/22/business/wo...,"The Federal Reserve, responding to an internat..."
3,0,"August 25, 2015August 25, 2015 7:28 am",https://news.blogs.nytimes.com/2015/08/25/morn...,CHINA CUTS RATES AFTER SHANGHAI STOCKS PLUNGE ...
4,0,"DEC. 8, 2010",https://www.nytimes.com/2010/12/09/opinion/09t...,There are compelling reasons why Congress shou...
5,0,"June 29, 2018",https://www.nytimes.com/2018/06/29/us/politics...,"— Larry Kudlow, the White House economic advi..."
6,0,,https://www.nytimes.com/2003/06/10/business/fo...,By signaling that he is prepared to cut intere...
7,0,,https://www.nytimes.com/2000/11/05/weekinrevie...,A chart last Sunday illustrating definitions o...
8,0,"Sept. 15, 2015",https://www.nytimes.com/2015/09/16/business/ec...,WASHINGTON — Data released on Tuesday revealed...
9,0,"Nov. 15, 2016",https://www.nytimes.com/2016/11/16/business/ec...,The harvest had just begun when agents from th...

In [36]:
text_dfs8_1001to2000.columns = ['index','date', 'url','article']

In [37]:
text_dfs8_1001to2000.head(10)

,index,date,url,article
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...
1,0,"July 9, 2018",https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec..."
2,0,"JAN. 22, 2008JAN. 21, 2008JAN. 22, 2008JAN. 22...",https://www.nytimes.com/2008/01/22/business/wo...,"The Federal Reserve, responding to an internat..."
3,0,"August 25, 2015August 25, 2015 7:28 am",https://news.blogs.nytimes.com/2015/08/25/morn...,CHINA CUTS RATES AFTER SHANGHAI STOCKS PLUNGE ...
4,0,"DEC. 8, 2010",https://www.nytimes.com/2010/12/09/opinion/09t...,There are compelling reasons why Congress shou...
5,0,"June 29, 2018",https://www.nytimes.com/2018/06/29/us/politics...,"— Larry Kudlow, the White House economic advi..."
6,0,,https://www.nytimes.com/2003/06/10/business/fo...,By signaling that he is prepared to cut intere...
7,0,,https://www.nytimes.com/2000/11/05/weekinrevie...,A chart last Sunday illustrating definitions o...
8,0,"Sept. 15, 2015",https://www.nytimes.com/2015/09/16/business/ec...,WASHINGTON — Data released on Tuesday revealed...
9,0,"Nov. 15, 2016",https://www.nytimes.com/2016/11/16/business/ec...,The harvest had just begun when agents from th...

### The below code applies the previously defined 'regex_date' function to the 'url' column of the dataframe to extract the date in an appropriate format. 

### The remainder of this notebook consists of the creation and storage via pickling of different dataframes containing article text, url, and date content. This process is repeated until ultimately the ~19,000 articles are all stored in memory.

In [38]:
text_dfs8_1001to2000['url_date'] = text_dfs8_1001to2000['url'].apply(regex_date)

In [39]:
text_dfs8_1001to2000.head()

,index,date,url,article,url_date
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...,2001-01-16
1,0,"July 9, 2018",https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec...",2018-07-09
2,0,"JAN. 22, 2008JAN. 21, 2008JAN. 22, 2008JAN. 22...",https://www.nytimes.com/2008/01/22/business/wo...,"The Federal Reserve, responding to an internat...",2008-01-22
3,0,"August 25, 2015August 25, 2015 7:28 am",https://news.blogs.nytimes.com/2015/08/25/morn...,CHINA CUTS RATES AFTER SHANGHAI STOCKS PLUNGE ...,2015-08-25
4,0,"DEC. 8, 2010",https://www.nytimes.com/2010/12/09/opinion/09t...,There are compelling reasons why Congress shou...,2010-12-09

In [40]:
pickle.dump( text_dfs8_1001to2000, open( "text_dfs8_1001to2000", "wb" ) )

In [41]:
url_list2001to3000 = url_list[2001:3000]

In [42]:
len(url_list2001to3000)

999

In [43]:
text_dfs8_2001to3000 = [get_text1(url) for url in url_list2001to3000]

In [44]:
text_dfs8_2001to3000 = pd.concat(text_dfs8_2001to3000).reset_index()

In [45]:
text_dfs8_2001to3000.shape

(999, 4)

In [46]:
text_dfs8_2001to3000.columns = ['index','date', 'url','article']

In [47]:
text_dfs8_2001to3000['url_date'] = text_dfs8_2001to3000['url'].apply(regex_date)

In [48]:
text_dfs8_2001to3000.head(10)

,index,date,url,article,url_date
0,0,"JULY 10, 2011JULY 10, 2011SEP 5SEP 1AUG 28AUG ...",https://www.nytimes.com/2011/07/11/opinion/11d...,The Republican Party’s strategy in the debt-ce...,2011-07-11
1,0,"JAN. 5, 2009",https://www.nytimes.com/2009/01/06/business/06...,The Securities and Exchange Commission needs t...,2009-01-06
2,0,"August 6, 2013 2:56 pm",https://douthat.blogs.nytimes.com/2013/08/06/r...,"This National Journal piece, the latest to mis...",2013-08-06
3,0,"OCT. 8, 2008MAY 11MAY 11MAY 4APR 27APR 16",https://www.nytimes.com/2008/10/09/business/yo...,It’s a question we’ve all asked in our darker ...,2008-10-09
4,0,,https://www.nytimes.com/interactive/2009/03/06...,,2009-03-06
5,0,"JUNE 20, 2013",https://www.nytimes.com/2013/06/21/us/21iht-le...,NEW YORK — The rich are getting richer. That’...,2013-06-21
6,0,"APRIL 4, 2009",https://www.nytimes.com/2009/04/05/weekinrevie...,WASHINGTON — As he cashiered the head of one o...,2009-04-05
7,0,"July 19, 2011 10:00 am",https://economix.blogs.nytimes.com/2011/07/19/...,"Yet more on the consumer bust, this time from ...",2011-07-19
8,0,"NOV. 13, 2006",https://www.nytimes.com/2006/11/13/opinion/13h...,“America moved me all over again — it was an a...,2006-11-13
9,0,"APRIL 8, 2008APRIL 8, 2008APRIL 8, 2008APRIL 8...",https://www.nytimes.com/2008/04/08/us/politics...,The resignation of Senator Hillary Rodham Clin...,2008-04-08

In [49]:
pickle.dump( text_dfs8_2001to3000, open( "text_dfs8_2001to3000", "wb" ) )

In [50]:
#text_dfs8 = text_dfs8.dropna(subset = ['url','article'])

In [59]:
text_dfs8_2001to3000_test = text_dfs8_2001to3000

In [63]:
text_dfs8_2001to3000_test =  text_dfs8_2001to3000_test.dropna()

In [64]:
text_dfs8_2001to3000_test

,index,date,url,article,url_date
0,0,"JULY 10, 2011JULY 10, 2011SEP 5SEP 1AUG 28AUG ...",https://www.nytimes.com/2011/07/11/opinion/11d...,The Republican Party’s strategy in the debt-ce...,2011-07-11
1,0,"JAN. 5, 2009",https://www.nytimes.com/2009/01/06/business/06...,The Securities and Exchange Commission needs t...,2009-01-06
2,0,"August 6, 2013 2:56 pm",https://douthat.blogs.nytimes.com/2013/08/06/r...,"This National Journal piece, the latest to mis...",2013-08-06
3,0,"OCT. 8, 2008MAY 11MAY 11MAY 4APR 27APR 16",https://www.nytimes.com/2008/10/09/business/yo...,It’s a question we’ve all asked in our darker ...,2008-10-09
4,0,,https://www.nytimes.com/interactive/2009/03/06...,,2009-03-06
5,0,"JUNE 20, 2013",https://www.nytimes.com/2013/06/21/us/21iht-le...,NEW YORK — The rich are getting richer. That’...,2013-06-21
6,0,"APRIL 4, 2009",https://www.nytimes.com/2009/04/05/weekinrevie...,WASHINGTON — As he cashiered the head of one o...,2009-04-05
7,0,"July 19, 2011 10:00 am",https://economix.blogs.nytimes.com/2011/07/19/...,"Yet more on the consumer bust, this time from ...",2011-07-19
8,0,"NOV. 13, 2006",https://www.nytimes.com/2006/11/13/opinion/13h...,“America moved me all over again — it was an a...,2006-11-13
9,0,"APRIL 8, 2008APRIL 8, 2008APRIL 8, 2008APRIL 8...",https://www.nytimes.com/2008/04/08/us/politics...,The resignation of Senator Hillary Rodham Clin...,2008-04-08
10,0,"DEC. 29, 2008DEC. 28, 2008DEC. 28, 2008",https://www.nytimes.com/2008/12/30/washington/...,WASHINGTON — Republican Congressional leaders ...,2008-12-30
11,0,"Dec. 18, 2014",https://www.nytimes.com/2014/12/19/business/wh...,What happens when you turn over regulatory res...,2014-12-19
12,0,"FEB. 14, 2018",https://www.nytimes.com/2018/02/14/business/de...,Good Wednesday. Here’s what we’re watching:• F...,2018-02-14
13,0,"NOV. 19, 2009",https://www.nytimes.com/2009/11/20/business/gl...,PARIS — China has helped to pull developed cou...,2009-11-20
14,0,,https://www.nytimes.com/2004/08/05/business/fe...,Despite a lull in economic growth and anxiety ...,2004-08-05
15,0,,https://www.nytimes.com/2003/11/01/opinion/l-g...,"To the Editor:Paul Krugman (column, Oct. 31) a...",2003-11-01
16,0,"JUNE 2, 2006",https://www.nytimes.com/2006/06/02/opinion/02m...,LAST month saw one of the sharpest drops in co...,2006-06-02
17,0,"MARCH 22, 2009",https://www.nytimes.com/2009/03/23/opinion/23s...,IN what may come to be the definitive line abo...,2009-03-23
18,0,"March 7, 2014 9:18 am",https://economix.blogs.nytimes.com/2014/03/07/...,The numbers were decent. The economy shook off...,2014-03-07
19,0,"FEB. 2, 2008FEB. 25, 2015FEB. 25, 2015",https://www.nytimes.com/2008/02/02/business/02...,"The nation’s employers eliminated 17,000 jobs ...",2008-02-02
20,0,"JAN. 28, 2007MARCH 7, 2015AUG 31AUG 24AUG 10JU...",https://www.nytimes.com/2007/01/28/business/yo...,"LAST week, Mayor Michael R. Bloomberg and Sena...",2007-01-28
21,0,"AUG. 4, 2011AUG. 4, 2011AUG. 4, 2011AUG. 4, 20...",https://www.nytimes.com/2011/08/05/us/politics...,"The debate over raising the debt ceiling, whic...",2011-08-05
22,0,,https://www.nytimes.com/2000/12/31/business/ec...,WHEN Bill Clinton moved into the White House e...,2000-12-31
23,0,"May 14, 2009 7:09 am",https://dealbook.nytimes.com/2009/05/14/lehman...,"Lehman Brothers, which sent global markets int...",2009-05-14
24,0,"JAN. 30, 2009",https://www.nytimes.com/2009/01/31/business/ec...,"First layoffs, then lawsuits.More workers are ...",2009-01-31
25,0,,https://www.nytimes.com/2003/07/02/business/fe...,Pessimism about the Japanese economy is slowly...,2003-07-02
26,0,,https://www.nytimes.com/2004/05/12/business/gr...,The United States and Asia are leaving Europe ...,2004-05-12
27,0,"OCT. 9, 2004",https://www.nytimes.com/2004/10/09/business/09...,Financial markets reacted sharply yesterday to...,2004-10-09
28,0,"APRIL 27, 2013",https://www.nytimes.com/2013/04/28/opinion/sun...,"At first glance, the latest economic growth re...",2013-04-28
30,0,"AUG. 27, 2009SEP 3AUG 31AUG 30AUG 27AUG 26",https://www.nytimes.com/2009/08/28/opinion/28k...,So new budget projections show a cumulative de...,2009-08-28
...,...,...,...,...,...
967,0,"MAY 6, 2010MAY 6, 2010MAY 6, 2010",https://www.nytimes.com/2010/05/07/business/07...,After a blockbuster March buoyed by brisk East...,2010-05-07
968,0,"FEB. 19, 2010",https://www.nytimes.com/2010/02/20/opinion/20i...,The mere suggestion that the United States inc...,2010-02-20
969,0,"JAN. 16, 2009",https://www.nytimes.com/2009/01/17/business/me...,"And then there was one.Not long ago, three tru...",2009-01-17
970,0,"JUNE 11, 2006",https://www.nytimes.com/2006/06/11/magazine/11...,Think of the economy of the United States as a...,2006-06-11
971,0,"APRIL 18, 2009",https://www.nytimes.com/2009/04/19/business/me...,THE world is in the throes of an unprecedented...,2009-04-19
972,0,"APRIL 6, 2013AUG 31AUG 24AUG 10JUL 27JUL 20",https://www.nytimes.com/2013/04/07/business/an...,MANY problems are so complex that even if we h...,2013-04-07
973,0,"JULY 2, 2010",https://www.nytimes.com/2010/07/03/business/03...,"“We’ve gotten our sea legs,” said Phil Angelid...",2010-07-03
974,0,"MARCH 10, 2009SEP 4AUG 28AUG 14AUG 8AUG 7",https://www.nytimes.com/2009/03/11/opinion/11f...,It’s always great to see the stock market come...,2009-03-11
975,0,"APRIL 19, 2009",https://www.nytimes.com/2009/04/20/us/politics...,As they seek to jolt the economy out of recess...,2009-04-20
976,0,"OCT. 7, 2012",https://www.nytimes.com/2012/10/08/business/ec...,ECONOMIC REPORTS Data to be released will incl...,2012-10-08
977,0,"MARCH 6, 2009AUG. 22, 2011AUG. 22, 2011",https://www.nytimes.com/2009/03/07/business/ec...,Amid the worst economic downturn of their care...,2009-03-07
979,0,"Jan. 26, 2018",https://www.nytimes.com/2018/01/26/business/tr...,"DAVOS, Switzerland — No one was declaring Pres...",2018-01-26
980,0,"NOV. 7, 2012NOV. 7, 2012NOV. 7, 2012AUG 31AUG ...",https://www.nytimes.com/2012/11/08/opinion/kri...,This was one that the Republicans really shoul...,2012-11-08
982,0,"MAY 6, 2011",https://www.nytimes.com/2011/05/07/business/ec...,"For three straight months, the nation’s employ...",2011-05-07
983,0,"DEC. 13, 2010",https://www.nytimes.com/2010/12/14/business/ec...,"To many manufacturing companies, the tax cut p...",2010-12-14
984,0,"APRIL 30, 2008SEP 4AUG 28AUG 14AUG 8AUG 7",https://www.nytimes.com/2008/04/30/opinion/30f...,It is great to see that we finally have some n...,2008-04-30
985,0,"April 14, 2010 10:34 am",https://dealbook.nytimes.com/2010/04/14/u-s-mu...,"The Federal Reserve chairman, Ben S. Bernanke,...",2010-04-14
986,0,"SEPT. 28, 2011",https://www.nytimes.com/2011/09/29/business/ec...,The stock market may be ahead of the economy. ...,2011-09-29
987,0,"Feb. 16, 2018",https://www.nytimes.com/2018/02/16/your-money/...,The stock market has been shaken by turbulence...,2018-02-16
988,0,"July 12, 2015",https://www.nytimes.com/2015/07/13/business/ri...,When the California Labor Commissioner’s Offic...,2015-07-13
989,0,"SEPT. 25, 2008",https://www.nytimes.com/2008/09/26/opinion/26f...,Lawmakers were still wrangling Thursday night ...,2008-09-26
990,0,"SEPT. 16, 2008SEPT. 16, 2008SEPT. 16, 2008SEPT...",https://www.nytimes.com/2008/09/17/business/ec...,Federal Reserve policy makers kept their bench...,2008-09-17
991,0,,https://www.nytimes.com/2003/04/03/business/fa...,Factory orders dropped 1.5 percent in February...,2003-04-03
992,0,"DEC. 15, 2011",https://www.nytimes.com/2011/12/16/business/ec...,WASHINGTON (Reuters) — The number of Americans...,2011-12-16
993,0,"APRIL 14, 2010APRIL 14, 2010APRIL 14, 2010",https://www.nytimes.com/2010/04/15/business/ec...,WASHINGTON — The Federal Reserve chairman said...,2010-04-15
994,0,,https://www.nytimes.com/2003/10/26/opinion/mar...,Though it has taken a breather in the past wee...,2003-10-26
995,0,"MARCH 3, 2009MARCH 3, 2009MARCH 3, 2009",https://www.nytimes.com/2009/03/04/us/politics...,WASHINGTON — Prime Minister Gordon Brown of Br...,2009-03-04
996,0,,https://www.nytimes.com/2002/10/22/business/in...,The index of leading economic indicators fell ...,2002-10-22
997,0,,https://www.nytimes.com/2002/03/03/business/ec...,"AFTER a jagged descent lasting two decades, th...",2002-03-03
998,0,"June 1, 2014",https://www.nytimes.com/2014/06/02/opinion/ame...,WASHINGTON — IF you think your commute is gett...,2014-06-02

In [71]:
text_dfs8_2001to3000_test.isnull().values.sum()

0

In [74]:
text_dfs8_2001to3000_test.shape

(966, 5)

In [76]:
text_dfs8_1001to2000.head(10)

,index,date,url,article,url_date
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...,2001-01-16
1,0,"July 9, 2018",https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec...",2018-07-09
2,0,"JAN. 22, 2008JAN. 21, 2008JAN. 22, 2008JAN. 22...",https://www.nytimes.com/2008/01/22/business/wo...,"The Federal Reserve, responding to an internat...",2008-01-22
3,0,"August 25, 2015August 25, 2015 7:28 am",https://news.blogs.nytimes.com/2015/08/25/morn...,CHINA CUTS RATES AFTER SHANGHAI STOCKS PLUNGE ...,2015-08-25
4,0,"DEC. 8, 2010",https://www.nytimes.com/2010/12/09/opinion/09t...,There are compelling reasons why Congress shou...,2010-12-09
5,0,"June 29, 2018",https://www.nytimes.com/2018/06/29/us/politics...,"— Larry Kudlow, the White House economic advi...",2018-06-29
6,0,,https://www.nytimes.com/2003/06/10/business/fo...,By signaling that he is prepared to cut intere...,2003-06-10
7,0,,https://www.nytimes.com/2000/11/05/weekinrevie...,A chart last Sunday illustrating definitions o...,2000-11-05
8,0,"Sept. 15, 2015",https://www.nytimes.com/2015/09/16/business/ec...,WASHINGTON — Data released on Tuesday revealed...,2015-09-16
9,0,"Nov. 15, 2016",https://www.nytimes.com/2016/11/16/business/ec...,The harvest had just begun when agents from th...,2016-11-16

In [80]:
abc = text_dfs8_1001to2000

In [81]:
abc.dropna()

,index,date,url,article,url_date
0,0,,https://www.nytimes.com/2001/01/16/nyregion/c-...,A chart of financial indicators at the bottom ...,2001-01-16
1,0,"July 9, 2018",https://www.nytimes.com/2018/07/09/opinion/tru...,"According to early indications, recent U.S. ec...",2018-07-09
2,0,"JAN. 22, 2008JAN. 21, 2008JAN. 22, 2008JAN. 22...",https://www.nytimes.com/2008/01/22/business/wo...,"The Federal Reserve, responding to an internat...",2008-01-22
3,0,"August 25, 2015August 25, 2015 7:28 am",https://news.blogs.nytimes.com/2015/08/25/morn...,CHINA CUTS RATES AFTER SHANGHAI STOCKS PLUNGE ...,2015-08-25
4,0,"DEC. 8, 2010",https://www.nytimes.com/2010/12/09/opinion/09t...,There are compelling reasons why Congress shou...,2010-12-09
5,0,"June 29, 2018",https://www.nytimes.com/2018/06/29/us/politics...,"— Larry Kudlow, the White House economic advi...",2018-06-29
6,0,,https://www.nytimes.com/2003/06/10/business/fo...,By signaling that he is prepared to cut intere...,2003-06-10
7,0,,https://www.nytimes.com/2000/11/05/weekinrevie...,A chart last Sunday illustrating definitions o...,2000-11-05
8,0,"Sept. 15, 2015",https://www.nytimes.com/2015/09/16/business/ec...,WASHINGTON — Data released on Tuesday revealed...,2015-09-16
9,0,"Nov. 15, 2016",https://www.nytimes.com/2016/11/16/business/ec...,The harvest had just begun when agents from th...,2016-11-16
11,0,,https://www.nytimes.com/2001/02/09/us/happily-...,"During the presidential campaign, Al Gore port...",2001-02-09
12,0,"APRIL 25, 2010",https://www.nytimes.com/2010/04/26/business/26...,ECONOMIC REPORTS Data will include the Standa...,2010-04-26
13,0,"APRIL 28, 2011SEP 3AUG 31AUG 30AUG 27AUG 26",https://www.nytimes.com/2011/04/29/opinion/29k...,Last month more than 14 million Americans were...,2011-04-29
14,0,"JUNE 27, 2011AUG 31AUG 24AUG 10AUG 3JUL 27",https://www.nytimes.com/2011/06/28/opinion/28i...,NEW YORK — The philosopher Isaiah Berlin once ...,2011-06-28
16,0,"DEC. 15, 2008DEC. 9, 2008DEC. 9, 2008",https://www.nytimes.com/2008/12/16/opinion/lwe...,To the Editor:Re “Where Are the New Jobs for W...,2008-12-16
17,0,"JUNE 22, 2011JUNE 22, 2011JUNE 22, 2011, 9:24 ...",https://www.nytimes.com/2011/06/23/business/ec...,"WASHINGTON — And at the end of June, the Feder...",2011-06-23
19,0,"MAY 22, 2009FEB. 17, 2015FEB. 17, 2015",https://www.nytimes.com/2009/05/23/business/ec...,"FOR many years, unemployment in the United Sta...",2009-05-23
20,0,"MAY 19, 2010",https://www.nytimes.com/2010/05/20/business/20...,WASHINGTON — The Federal Reserve indicated tha...,2010-05-20
21,0,,https://www.nytimes.com/2004/01/08/business/ec...,"''THIS administration today, here and now, dec...",2004-01-08
22,0,"OCT. 10, 2008",https://www.nytimes.com/2008/10/11/us/politics...,Senator John McCain proposed on Friday that in...,2008-10-11
23,0,"July 23, 2012 7:00 am",https://boss.blogs.nytimes.com/2012/07/23/this...,DashboardA daily roundup of small-business dev...,2012-07-23
24,0,"DEC. 6, 2006",https://www.nytimes.com/2006/12/06/business/06...,A revised Labor Department report on worker pr...,2006-12-06
25,0,"OCT. 19, 2008FEB. 22, 2015OCT. 17, 2008FEB. 22...",https://www.nytimes.com/2008/10/20/business/20...,Fear is running high on Wall Street. Just look...,2008-10-20
26,0,"April 2, 2009 12:00 am",https://learning.blogs.nytimes.com/2009/04/02/...,Note: This lesson was originally published on ...,2009-04-02
27,0,"JUNE 21, 2011MAY 29MAY 22MAY 15MAY 8MAY 1",https://www.nytimes.com/2011/06/22/business/ec...,Republicans say they won’t raise taxes. Democr...,2011-06-22
28,0,,https://www.nytimes.com/2006/01/07/politics/07...,"WASHINGTON, Jan. 6 - The United States generat...",2006-01-07
29,0,"May 28, 2015",https://www.nytimes.com/2015/05/29/business/ec...,WASHINGTON — Americans signed contracts to buy...,2015-05-29
30,0,"AUG. 4, 2012AUG. 4, 2012AUG. 4, 2012AUG. 4, 20...",https://www.nytimes.com/2012/08/05/business/th...,"SMYRNA, Tenn. — The dairy farms that once drap...",2012-08-05
31,0,"MARCH 3, 2009MARCH 3, 2009MARCH 3, 2009",https://www.nytimes.com/2009/03/04/us/politics...,WASHINGTON — The chairman of the Federal Reser...,2009-03-04
32,0,"September 9, 2014 12:06 pm",https://boss.blogs.nytimes.com/2014/09/09/toda...,"Whatâs affecting me, my clients and other sm...",2014-09-09
...,...,...,...,...,...
968,0,"DEC. 7, 2010",https://www.nytimes.com/2010/12/08/business/08...,The bond market on Tuesday had one of its wors...,2010-12-08
969,0,,https://www.nytimes.com/2014/06/07/business/la...,,2014-06-07
970,0,"OCT. 16, 2008",https://www.nytimes.com/2008/10/16/opinion/16c...,"In our interconnected world, the American fina...",2008-10-16
971,0,"SEPT. 5, 2012MAY 24, 2011MAY 24, 2011",https://www.nytimes.com/2012/09/06/us/like-the...,WASHINGTON — From Uncle Sam saying “I want YOU...,2012-09-06
972,0,"NOV. 17, 2010",https://www.nytimes.com/2010/11/18/business/18...,Stocks were little changed on Wednesday as con...,2010-11-18
973,0,,https://www.nytimes.com/2001/12/21/us/gop-push...,When President Bush's push for an economic sti...,2001-12-21
974,0,,https://www.nytimes.com/2002/12/08/weekinrevie...,IF you measure the success of a president by j...,2002-12-08
975,0,"FEB. 22, 2013FEB. 22, 2013AUG 29AUG 26AUG 23AU...",https://www.nytimes.com/2013/02/23/opinion/blo...,"It’s crunch time.The sequester’s automatic, ac...",2013-02-23
976,0,,https://www.nytimes.com/2003/03/30/business/ec...,"RIGHT now, the war in Iraq is the most importa...",2003-03-30
977,0,"May 18, 2016May 18, 2016 6:27 am",https://news.blogs.nytimes.com/2016/05/18/morn...,A TALE OF TWO SILICON VALLEYS | Lending Club...,2016-05-18
978,0,"OCT. 25, 2011OCT. 25, 2011OCT. 25, 2011OCT. 25...",https://www.nytimes.com/2011/10/26/us/politics...,"With Election Day just over a year away, a dee...",2011-10-26
979,0,"January 14, 2015 8:30 am",https://dealbook.nytimes.com/2015/01/14/wells-...,Many people doubt the strength of the United S...,2015-01-14
980,0,"January 14, 2010 8:27 pm",https://dealbook.nytimes.com/2010/01/14/the-st...,"From Eric Dash, a DealBook colleague:The idea ...",2010-01-14
981,0,"AUG. 20, 2007",https://www.nytimes.com/2007/08/20/business/20...,EYE ON THE ECONOMY Wall Street will be looking...,2007-08-20
982,0,"OCT. 16, 2008OCT. 16, 2008OCT. 16, 2008OCT. 16...",https://www.nytimes.com/2008/10/16/opinion/16b...,DublinIN the ravening years of the Celtic Tige...,2008-10-16
984,0,"JUNE 25, 2009JULY 29, 2013JULY 22, 2009JULY 21...",https://www.nytimes.com/2009/06/26/business/26...,WASHINGTON — It has become the trillion-dollar...,2009-06-26
985,0,,https://www.nytimes.com/2018/06/05/pageoneplus...,FRONT PAGEAn article on May 30 about the eques...,2018-06-05
986,0,"MAY 1, 2009",https://www.nytimes.com/2009/05/02/opinion/02h...,The incredibly clueless stewards of the incred...,2009-05-02
987,0,"OCT. 2, 2010SEPT. 25, 2010SEPT. 25, 2010",https://www.nytimes.com/2010/10/03/business/03...,To the Editor:In “What the Rich Don’t Need” (E...,2010-10-03
988,0,"FEB. 25, 2006",https://www.nytimes.com/2006/02/25/business/wo...,"Correction AppendedHOUSTON, Feb. 24 - Despite ...",2006-02-25
989,0,,https://www.nytimes.com/2014/07/04/business/jo...,,2014-07-04
990,0,"JULY 28, 2005",https://www.nytimes.com/2005/07/28/business/wo...,"WASHINGTON, Thursday, July 28 - The House of R...",2005-07-28
991,0,,https://www.nytimes.com/2000/06/15/business/re...,"The national inflation rate, which has been in...",2000-06-15
993,0,,https://www.nytimes.com/2004/08/11/business/fe...,The Federal Reserve increased short-term inter...,2004-08-11
994,0,"April 14, 2010 1:52 pm",https://dealbook.nytimes.com/2010/04/14/obama-...,In the face of stiff opposition from Senate Re...,2010-04-14
995,0,"May 17, 2017",https://www.nytimes.com/2017/05/17/business/de...,"It took nearly a decade, but debt has made a c...",2017-05-17
996,0,"APRIL 9, 2009",https://www.nytimes.com/2009/04/10/business/10...,"Only a year ago, all the stars appeared to be ...",2009-04-10
997,0,"APRIL 20, 2008FEB. 24, 2015FEB. 24, 2015",https://www.nytimes.com/2008/04/20/magazine/20...,A CLEAR SENSE OF EMISSION: Carbon-dioxide equi...,2008-04-20
998,0,,https://www.nytimes.com/2002/11/19/business/wh...,These are gloomy times for those who plead for...,2002-11-19
999,0,"SEPT. 5, 4800",https://www.nytimes.com/2001/11/11/business/pe...,Perhaps people are following President Bush's ...,2001-11-11

In [82]:
url_list3001to4000 = url_list[3001:4000]

In [83]:
text_dfs8_3001to4000 = [get_text1(url) for url in url_list3001to4000]

In [84]:
text_dfs8_3001to4000 = pd.concat(text_dfs8_3001to4000).reset_index()

In [86]:
text_dfs8_3001to4000.columns = ['index','date', 'url','article']

In [88]:
text_dfs8_3001to4000_testing = text_dfs8_3001to4000
text_dfs8_3001to4000.head(4)

,index,date,url,article
0,0,"May 2, 2017",https://www.nytimes.com/2017/05/02/business/au...,"For seven years, the steadily expanding auto i..."
1,0,"Feb. 1, 2015",https://www.nytimes.com/2015/02/02/business/ec...,Here are some of the top business stories to p...
2,0,"SEPT. 14, 2012",https://www.nytimes.com/2012/09/15/business/ec...,An increase in the cost of gasoline pushed con...
3,0,"FEB. 26, 2013FEB. 26, 2013FEB. 26, 2013FEB. 26...",https://www.nytimes.com/2013/02/27/business/ec...,"WASHINGTON — The Federal Reserve chairman, Ben..."

In [90]:
text_dfs8_3001to4000_testing = text_dfs8_3001to4000_testing.dropna()

In [91]:
text_dfs8_3001to4000_testing.isnull().values.sum()

0

In [92]:
text_dfs8_3001to4000_testing['url_date'] = text_dfs8_3001to4000_testing['url'].apply(regex_date)

In [106]:
text_dfs8_3001to4000_testing.head(5)

,index,date,url,article,url_date
0,0,"May 2, 2017",https://www.nytimes.com/2017/05/02/business/au...,"For seven years, the steadily expanding auto i...",2017-05-02
1,0,"Feb. 1, 2015",https://www.nytimes.com/2015/02/02/business/ec...,Here are some of the top business stories to p...,2015-02-02
2,0,"SEPT. 14, 2012",https://www.nytimes.com/2012/09/15/business/ec...,An increase in the cost of gasoline pushed con...,2012-09-15
3,0,"FEB. 26, 2013FEB. 26, 2013FEB. 26, 2013FEB. 26...",https://www.nytimes.com/2013/02/27/business/ec...,"WASHINGTON — The Federal Reserve chairman, Ben...",2013-02-27
4,0,"Aug. 30, 2016",https://www.nytimes.com/2016/08/31/business/ec...,What’s ahead for the American economy?That que...,2016-08-31

In [94]:
pickle.dump( text_dfs8_3001to4000_testing, open( "text_dfs8_3001to4000_testing", "wb" ) )

In [95]:
url_list4001to5000 = url_list[4001:5000]

In [96]:
text_dfs8_4001to5000 = [get_text1(url) for url in url_list4001to5000]

text_dfs8_4001to5000 = pd.concat(text_dfs8_4001to5000).reset_index()

In [98]:
text_dfs8_4001to5000

,index,0,1,2
0,0,"MAY 4, 2009",https://www.nytimes.com/2009/05/05/opinion/05t...,There is something wrong with a system where s...
1,0,,https://www.nytimes.com/2001/11/07/opinion/whi...,Yesterday the Federal Reserve cut interest rat...
2,0,"Dec. 4, 2014",https://www.nytimes.com/2014/12/04/opinion/rog...,New York has always been a pretty good baromet...
3,0,"APRIL 21, 2008",https://www.nytimes.com/2008/04/21/business/re...,THE dream of retiring to a Tuscan villa or a b...
4,0,"June 20, 2013 12:01 am",https://economix.blogs.nytimes.com/2013/06/20/...,"Simon Johnson, former chief economist of the I..."
5,0,"MARCH 29, 2011MARCH 29, 2011MAY 29MAY 22MAY 15...",https://www.nytimes.com/2011/03/30/business/ec...,WASHINGTONWhenever officials at the Federal Re...
6,0,,https://www.nytimes.com/2003/12/11/business/ec...,"THE City of Indianapolis, it has been reported..."
7,0,"JULY 8, 2009JULY 8, 2009JULY 8, 2009",https://www.nytimes.com/2009/07/09/us/politics...,"WASHINGTON — At his inauguration in January, P..."
8,0,"SEPT. 5, 8800",https://www.nytimes.com/2005/05/19/business/19...,Inflation slowed in April from its fast pace i...
9,0,"May 24, 2015",https://www.nytimes.com/2015/05/25/business/pu...,"MIAMI — For the Ingram clan, working for the M..."
10,0,"DEC. 9, 2011DEC. 9, 2011DEC. 9, 2011",https://www.nytimes.com/2011/12/10/us/politics...,"WASHINGTON — Last year, the Obama administrati..."
11,0,"January 12, 2012 4:49 pm",https://economix.blogs.nytimes.com/2012/01/12/...,What Mitt Romney a few days ago called âthe ...
12,0,"MARCH 25, 2011MARCH 25, 2011MARCH 25, 2011",https://www.nytimes.com/2011/03/26/business/26...,TO judge by the overall level of home sales in...
13,0,"AUG. 21, 2011",https://www.nytimes.com/2011/08/22/business/wo...,With the global economy sputtering and financi...
14,0,"NOV. 2, 2010NOV. 2, 2010NOV. 2, 2010NOV. 2, 20...",https://www.nytimes.com/2010/11/03/us/politics...,"WASHINGTONTwo years ago this week, triumphant ..."
15,0,,https://www.nytimes.com/2001/11/18/weekinrevie...,''THERE was a sense that this could be a turni...
16,0,"AUG. 17, 2010SEP 4AUG 28AUG 14AUG 8AUG 7",https://www.nytimes.com/2010/08/18/opinion/18f...,BerlinOver the past few weeks I’ve had a chanc...
17,0,"SEPT. 5, 6800",https://www.nytimes.com/2003/05/20/business/co...,The Conference Board's index of leading econom...
18,0,"NOV. 14, 2008",https://www.nytimes.com/2008/11/14/us/politics...,"As he prepares to take office, President-elect..."
19,0,,https://www.nytimes.com/2001/08/23/us/bush-pro...,"Ending a brief but giddy era of fiscal plenty,..."
20,0,"December 2, 2011 11:52 am",https://green.blogs.nytimes.com/2011/12/02/new...,The Environmental Protection Agency on Friday ...
21,0,"NOV. 14, 2009NOV 10NOV 3OCT 27OCT 13OCT 6",https://www.nytimes.com/2009/11/15/business/ec...,"ON Nov. 6, President Obama signed the Worker, ..."
22,0,"JUNE 23, 2010JUNE 23, 2010JUNE 23, 2010",https://www.nytimes.com/2010/06/24/business/ec...,The Federal Reserve’s policy-making arm said o...
23,0,"JAN. 18, 2008",https://www.nytimes.com/2008/01/18/business/18...,WASHINGTON — President Bush called on Friday f...
24,0,,https://www.nytimes.com/roomfordebate/2014/05/...,
25,0,"FEB. 16, 2011",https://www.nytimes.com/2011/02/17/business/ec...,Producer prices rose in January to their highe...
26,0,"Jan. 13, 2016",https://www.nytimes.com/2016/01/15/business/de...,HONG KONG — Global markets continued their jit...
27,0,"SEPT. 5, 800",https://www.nytimes.com/2002/03/31/business/da...,Stocks fell modestly last week as investors fe...
28,0,"MAY 24, 2008FEB. 23, 2015FEB. 23, 2015",https://www.nytimes.com/2008/05/24/business/24...,THE private mortgage market in the United Stat...
29,0,,https://www.nytimes.com/2003/08/29/business/ec...,The economy grew at a revised annual rate of 3...
...,...,...,...,...
969,0,"SEPT. 15, 2011",https://www.nytimes.com/2011/09/16/business/ec...,The rate of inflation in the United States slo...
970,0,"April 15, 2013 1:56 pm",https://economix.blogs.nytimes.com/2013/04/15/...,4/16/13 | Updated to reflect new figures on ho...
971,0,"JAN. 29, 2012JAN. 26, 2012JAN. 5, 2012JAN. 26,...",https://www.nytimes.com/2012/01/30/opinion/new...,The $259 billion in budget cuts over the next ...
972,0,"MAY 30, 2008",https://www.nytimes.com/2008/05/30/business/30...,The economy grew at a faster pace than origina...
973,0,"FEB. 15, 2011FEB. 14, 2011FEB. 14, 2011",https://www.nytimes.com/2011/02/16/world/ameri...,"CARACAS, Venezuela — Armed with a $9 billion r..."
974,0,"JULY 1, 2010",https://www.nytimes.com/2010/07/02/business/ec...,A record drop in pending home sales and a slow...
975,0,"JUNE 7, 2010",https://www.nytimes.com/2010/06/07/business/07...,ECONOMIC REPORTS Data will include consumer cr...
976,0,"June 10, 2014",https://www.nytimes.com/2014/06/11/business/in...,WASHINGTON — The World Bank has downgraded its...
977,0,"February 7, 2014 1:46 pm",https://economix.blogs.nytimes.com/2014/02/07/...,American unemployment has been declining for t...
978,0,"MARCH 18, 2013JUL 30JUL 26JUL 23JUL 19JUL 16",https://www.nytimes.com/2013/03/19/opinion/bro...,There is a statue outside the Federal Trade Co...
979,0,"Dec. 17, 2016",https://www.nytimes.com/2016/12/17/opinion/sun...,"Seven years ago, I joined the night shift at a..."
980,0,"Aug. 14, 2014",https://www.nytimes.com/2014/08/15/opinion/pau...,"It’s hard to believe, but almost six years hav..."
981,0,"April 2, 2018",https://www.nytimes.com/2018/04/02/opinion/tru...,These days almost everyone has the (justified)...
982,0,"Sept. 17, 2014",https://www.nytimes.com/2014/09/18/upshot/with...,If you bought health insurance at an Affordabl...
983,0,"JAN. 10, 2005",https://query.nytimes.com/gst/fullpage.html?re...,"To the Editor:Carol Adelman (""A High Quality o..."
984,0,"SEPT. 7, 2009",https://www.nytimes.com/2009/09/08/opinion/08h...,Maybe the economic stress has been too much. L...
985,0,"DEC. 5, 2012",https://www.nytimes.com/2012/12/06/business/ch...,WASHINGTON — Proposals to cap or otherwise lim...
986,0,"DEC. 24, 2004",https://www.nytimes.com/2004/12/24/business/24...,"WASHINGTON, Dec. 23 - The dollar hit another r..."
987,0,,https://www.nytimes.com/2001/10/05/opinion/l-g...,"To the Editor:Maureen Dowd (column, Oct. 3) sa..."
988,0,"APRIL 6, 2008",https://www.nytimes.com/2008/04/06/magazine/06...,"“You did moral hazard in 1998,” writes Steven ..."
989,0,,https://www.nytimes.com/2004/08/13/business/re...,United States retail sales rose last month and...
990,0,,https://www.nytimes.com/2003/10/03/us/poll-sho...,The public's confidence in President Bush's ab...
991,0,,https://www.nytimes.com/2000/05/19/business/fe...,Federal Reserve policy makers unanimously appr...
992,0,"FEB. 1, 2013FEB. 1, 2013FEB. 1, 2013FEB. 1, 20...",https://www.nytimes.com/2013/02/02/business/ec...,Political gridlock over fiscal policy didn’t p...
993,0,"MAY 19, 2007",https://www.nytimes.com/2007/05/19/business/19...,Stocks surged yesterday as another round of c...
994,0,"APRIL 18, 2008SEP 3AUG 31AUG 30AUG 27AUG 26",https://www.nytimes.com/2008/04/18/opinion/18k...,Will Barack Obama’s now famous “bitter” quote ...
995,0,"OCT. 3, 2008",https://www.nytimes.com/2008/10/05/fashion/sho...,"ParisONE hundred years or eight days ago, the..."
996,0,"APRIL 6, 2009",https://www.nytimes.com/2009/04/07/world/07sum...,WASHINGTON — It is an extraordinary number for...
997,0,"MAY 13, 2016MAY 18, 2016AUG 31AUG 24AUG 10JUL ...",https://www.nytimes.com/2016/05/15/upshot/what...,"We’re in the golden age of innovation, an era ..."
998,0,"May 31, 2017",https://www.nytimes.com/2017/05/31/opinion/tru...,With a week to sift through the Trump administ...

In [100]:

pickle.dump( text_dfs8_4001to5000, open( "text_dfs8_4001to5000_testing", "wb" ) )

In [101]:
text_dfs8_4001to5000.columns = ['index','date', 'url','article']

In [108]:
text_dfs8_4001to5000.head(2)

,index,date,url,article
0,0,"MAY 4, 2009",https://www.nytimes.com/2009/05/05/opinion/05t...,There is something wrong with a system where s...
1,0,,https://www.nytimes.com/2001/11/07/opinion/whi...,Yesterday the Federal Reserve cut interest rat...

In [110]:
text_dfs8_4001to5000_testing = text_dfs8_4001to5000
text_dfs8_4001to5000_testing.dropna(subset = ['url','article'])

,index,date,url,article
0,0,"MAY 4, 2009",https://www.nytimes.com/2009/05/05/opinion/05t...,There is something wrong with a system where s...
1,0,,https://www.nytimes.com/2001/11/07/opinion/whi...,Yesterday the Federal Reserve cut interest rat...
2,0,"Dec. 4, 2014",https://www.nytimes.com/2014/12/04/opinion/rog...,New York has always been a pretty good baromet...
3,0,"APRIL 21, 2008",https://www.nytimes.com/2008/04/21/business/re...,THE dream of retiring to a Tuscan villa or a b...
4,0,"June 20, 2013 12:01 am",https://economix.blogs.nytimes.com/2013/06/20/...,"Simon Johnson, former chief economist of the I..."
5,0,"MARCH 29, 2011MARCH 29, 2011MAY 29MAY 22MAY 15...",https://www.nytimes.com/2011/03/30/business/ec...,WASHINGTONWhenever officials at the Federal Re...
6,0,,https://www.nytimes.com/2003/12/11/business/ec...,"THE City of Indianapolis, it has been reported..."
7,0,"JULY 8, 2009JULY 8, 2009JULY 8, 2009",https://www.nytimes.com/2009/07/09/us/politics...,"WASHINGTON — At his inauguration in January, P..."
8,0,"SEPT. 5, 8800",https://www.nytimes.com/2005/05/19/business/19...,Inflation slowed in April from its fast pace i...
9,0,"May 24, 2015",https://www.nytimes.com/2015/05/25/business/pu...,"MIAMI — For the Ingram clan, working for the M..."
10,0,"DEC. 9, 2011DEC. 9, 2011DEC. 9, 2011",https://www.nytimes.com/2011/12/10/us/politics...,"WASHINGTON — Last year, the Obama administrati..."
11,0,"January 12, 2012 4:49 pm",https://economix.blogs.nytimes.com/2012/01/12/...,What Mitt Romney a few days ago called âthe ...
12,0,"MARCH 25, 2011MARCH 25, 2011MARCH 25, 2011",https://www.nytimes.com/2011/03/26/business/26...,TO judge by the overall level of home sales in...
13,0,"AUG. 21, 2011",https://www.nytimes.com/2011/08/22/business/wo...,With the global economy sputtering and financi...
14,0,"NOV. 2, 2010NOV. 2, 2010NOV. 2, 2010NOV. 2, 20...",https://www.nytimes.com/2010/11/03/us/politics...,"WASHINGTONTwo years ago this week, triumphant ..."
15,0,,https://www.nytimes.com/2001/11/18/weekinrevie...,''THERE was a sense that this could be a turni...
16,0,"AUG. 17, 2010SEP 4AUG 28AUG 14AUG 8AUG 7",https://www.nytimes.com/2010/08/18/opinion/18f...,BerlinOver the past few weeks I’ve had a chanc...
17,0,"SEPT. 5, 6800",https://www.nytimes.com/2003/05/20/business/co...,The Conference Board's index of leading econom...
18,0,"NOV. 14, 2008",https://www.nytimes.com/2008/11/14/us/politics...,"As he prepares to take office, President-elect..."
19,0,,https://www.nytimes.com/2001/08/23/us/bush-pro...,"Ending a brief but giddy era of fiscal plenty,..."
20,0,"December 2, 2011 11:52 am",https://green.blogs.nytimes.com/2011/12/02/new...,The Environmental Protection Agency on Friday ...
21,0,"NOV. 14, 2009NOV 10NOV 3OCT 27OCT 13OCT 6",https://www.nytimes.com/2009/11/15/business/ec...,"ON Nov. 6, President Obama signed the Worker, ..."
22,0,"JUNE 23, 2010JUNE 23, 2010JUNE 23, 2010",https://www.nytimes.com/2010/06/24/business/ec...,The Federal Reserve’s policy-making arm said o...
23,0,"JAN. 18, 2008",https://www.nytimes.com/2008/01/18/business/18...,WASHINGTON — President Bush called on Friday f...
24,0,,https://www.nytimes.com/roomfordebate/2014/05/...,
25,0,"FEB. 16, 2011",https://www.nytimes.com/2011/02/17/business/ec...,Producer prices rose in January to their highe...
26,0,"Jan. 13, 2016",https://www.nytimes.com/2016/01/15/business/de...,HONG KONG — Global markets continued their jit...
27,0,"SEPT. 5, 800",https://www.nytimes.com/2002/03/31/business/da...,Stocks fell modestly last week as investors fe...
28,0,"MAY 24, 2008FEB. 23, 2015FEB. 23, 2015",https://www.nytimes.com/2008/05/24/business/24...,THE private mortgage market in the United Stat...
29,0,,https://www.nytimes.com/2003/08/29/business/ec...,The economy grew at a revised annual rate of 3...
...,...,...,...,...
969,0,"SEPT. 15, 2011",https://www.nytimes.com/2011/09/16/business/ec...,The rate of inflation in the United States slo...
970,0,"April 15, 2013 1:56 pm",https://economix.blogs.nytimes.com/2013/04/15/...,4/16/13 | Updated to reflect new figures on ho...
971,0,"JAN. 29, 2012JAN. 26, 2012JAN. 5, 2012JAN. 26,...",https://www.nytimes.com/2012/01/30/opinion/new...,The $259 billion in budget cuts over the next ...
972,0,"MAY 30, 2008",https://www.nytimes.com/2008/05/30/business/30...,The economy grew at a faster pace than origina...
973,0,"FEB. 15, 2011FEB. 14, 2011FEB. 14, 2011",https://www.nytimes.com/2011/02/16/world/ameri...,"CARACAS, Venezuela — Armed with a $9 billion r..."
974,0,"JULY 1, 2010",https://www.nytimes.com/2010/07/02/business/ec...,A record drop in pending home sales and a slow...
975,0,"JUNE 7, 2010",https://www.nytimes.com/2010/06/07/business/07...,ECONOMIC REPORTS Data will include consumer cr...
976,0,"June 10, 2014",https://www.nytimes.com/2014/06/11/business/in...,WASHINGTON — The World Bank has downgraded its...
977,0,"February 7, 2014 1:46 pm",https://economix.blogs.nytimes.com/2014/02/07/...,American unemployment has been declining for t...
978,0,"MARCH 18, 2013JUL 30JUL 26JUL 23JUL 19JUL 16",https://www.nytimes.com/2013/03/19/opinion/bro...,There is a statue outside the Federal Trade Co...
979,0,"Dec. 17, 2016",https://www.nytimes.com/2016/12/17/opinion/sun...,"Seven years ago, I joined the night shift at a..."
980,0,"Aug. 14, 2014",https://www.nytimes.com/2014/08/15/opinion/pau...,"It’s hard to believe, but almost six years hav..."
981,0,"April 2, 2018",https://www.nytimes.com/2018/04/02/opinion/tru...,These days almost everyone has the (justified)...
982,0,"Sept. 17, 2014",https://www.nytimes.com/2014/09/18/upshot/with...,If you bought health insurance at an Affordabl...
983,0,"JAN. 10, 2005",https://query.nytimes.com/gst/fullpage.html?re...,"To the Editor:Carol Adelman (""A High Quality o..."
984,0,"SEPT. 7, 2009",https://www.nytimes.com/2009/09/08/opinion/08h...,Maybe the economic stress has been too much. L...
985,0,"DEC. 5, 2012",https://www.nytimes.com/2012/12/06/business/ch...,WASHINGTON — Proposals to cap or otherwise lim...
986,0,"DEC. 24, 2004",https://www.nytimes.com/2004/12/24/business/24...,"WASHINGTON, Dec. 23 - The dollar hit another r..."
987,0,,https://www.nytimes.com/2001/10/05/opinion/l-g...,"To the Editor:Maureen Dowd (column, Oct. 3) sa..."
988,0,"APRIL 6, 2008",https://www.nytimes.com/2008/04/06/magazine/06...,"“You did moral hazard in 1998,” writes Steven ..."
989,0,,https://www.nytimes.com/2004/08/13/business/re...,United States retail sales rose last month and...
990,0,,https://www.nytimes.com/2003/10/03/us/poll-sho...,The public's confidence in President Bush's ab...
991,0,,https://www.nytimes.com/2000/05/19/business/fe...,Federal Reserve policy makers unanimously appr...
992,0,"FEB. 1, 2013FEB. 1, 2013FEB. 1, 2013FEB. 1, 20...",https://www.nytimes.com/2013/02/02/business/ec...,Political gridlock over fiscal policy didn’t p...
993,0,"MAY 19, 2007",https://www.nytimes.com/2007/05/19/business/19...,Stocks surged yesterday as another round of c...
994,0,"APRIL 18, 2008SEP 3AUG 31AUG 30AUG 27AUG 26",https://www.nytimes.com/2008/04/18/opinion/18k...,Will Barack Obama’s now famous “bitter” quote ...
995,0,"OCT. 3, 2008",https://www.nytimes.com/2008/10/05/fashion/sho...,"ParisONE hundred years or eight days ago, the..."
996,0,"APRIL 6, 2009",https://www.nytimes.com/2009/04/07/world/07sum...,WASHINGTON — It is an extraordinary number for...
997,0,"MAY 13, 2016MAY 18, 2016AUG 31AUG 24AUG 10JUL ...",https://www.nytimes.com/2016/05/15/upshot/what...,"We’re in the golden age of innovation, an era ..."
998,0,"May 31, 2017",https://www.nytimes.com/2017/05/31/opinion/tru...,With a week to sift through the Trump administ...

In [111]:
text_dfs8_4001to5000_testing.shape

(999, 4)

In [112]:
text_dfs8_4001to5000_testing['url_date'] = text_dfs8_4001to5000_testing['url'].apply(regex_date)

In [115]:
(text_dfs8_4001to5000_testing.head(2))

,index,date,url,article,url_date
0,0,"MAY 4, 2009",https://www.nytimes.com/2009/05/05/opinion/05t...,There is something wrong with a system where s...,2009-05-05
1,0,,https://www.nytimes.com/2001/11/07/opinion/whi...,Yesterday the Federal Reserve cut interest rat...,2001-11-07

In [116]:
print(text_dfs8_4001to5000_testing.shape)

(999, 5)

In [117]:
url_list5001to7000 = url_list[5001:7000]

In [118]:
text_dfs8_5001to7000 = [get_text1(url) for url in url_list5001to7000]

In [119]:
text_dfs8_5001to7000 = pd.concat(text_dfs8_5001to7000).reset_index()

In [120]:
text_dfs8_5001to7000.columns = ['index','date', 'url','article']

In [121]:
text_dfs8_5001to7000.shape

(1999, 4)

In [122]:
text_dfs8_5001to7000.head(2)

,index,date,url,article
0,0,"JUNE 21, 2006",https://www.nytimes.com/2006/06/21/business/21...,Wall Street pared an earlier advance to end mi...
1,0,"Oct. 29, 2014",https://www.nytimes.com/2014/10/30/upshot/the-...,The most important thing to understand about t...

In [123]:
pickle.dump( text_dfs8_5001to7000, open( "text_dfs8_5001to7000_testing", "wb" ) )

In [125]:
text_dfs8_5001to7000_testing = text_dfs8_5001to7000

In [126]:
text_dfs8_5001to7000_testing.dropna()

,index,date,url,article
0,0,"JUNE 21, 2006",https://www.nytimes.com/2006/06/21/business/21...,Wall Street pared an earlier advance to end mi...
1,0,"Oct. 29, 2014",https://www.nytimes.com/2014/10/30/upshot/the-...,The most important thing to understand about t...
2,0,"JULY 16, 2010MAY 11MAY 11MAY 4APR 27APR 16",https://www.nytimes.com/2010/07/17/your-money/...,"Sometime next week, President Obama will final..."
3,0,"MAY 11, 2007MAY 7, 2007MAY 7, 2007",https://www.nytimes.com/2007/05/11/opinion/l11...,To the Editor:Lawrence Downes (Editorial Obse...
4,0,"SEPT. 6, 6800",https://www.nytimes.com/2002/12/21/us/democrat...,Faced with the certainty that President Bush c...
5,0,"Sept. 22, 2017",https://www.nytimes.com/2017/09/22/upshot/who-...,The most important job in global economics is ...
6,0,"DEC. 17, 2012",https://www.nytimes.com/2012/12/18/us/politics...,"ZEELAND, Mich. — The people who live here on t..."
7,0,,https://www.nytimes.com/2014/06/15/magazine/si...,Like any supersecret lab that’s supposedly try...
8,0,,https://www.nytimes.com/2002/01/27/weekinrevie...,"ENRON did it. So did Kmart. But they are far, ..."
9,0,"Nov. 29, 2016",https://www.nytimes.com/2016/11/29/business/ec...,The United States economy in the third quarter...
10,0,,https://www.nytimes.com/2001/11/07/us/nation-c...,Congressional Republicans stepped up attacks o...
11,0,"MAY 10, 2007MAY 10, 2007MAY 10, 2007",https://www.nytimes.com/2007/05/10/business/10...,"WASHINGTON, May 9 — The Federal Reserve acknow..."
12,0,"JULY 25, 2008",https://www.nytimes.com/2008/07/25/opinion/25v...,"WITH the nation embroiled in a housing crisis,..."
13,0,"MARCH 1, 2013",https://www.nytimes.com/2013/03/02/business/ec...,Busier factories and growing optimism among co...
14,0,"AUG. 26, 2005",https://www.nytimes.com/2005/08/26/business/26...,"It might still be 80 degrees outside, but, fou..."
15,0,"MAY 12, 2007",https://www.nytimes.com/2007/05/12/business/12...,"WASHINGTON, May 11 (AP) — Retail sales fell..."
16,0,,https://www.nytimes.com/2003/11/01/opinion/l-g...,To the Editor:Re ''Economy Records Speediest G...
17,0,"MARCH 15, 2008",https://www.nytimes.com/2008/03/15/business/15...,The government announced Friday that the cost ...
18,0,"OCT. 30, 2009",https://www.nytimes.com/2009/10/31/opinion/l31...,"To the Editor:Re “The Tenacity Question,” by D..."
19,0,"JULY 9, 2009",https://www.nytimes.com/2009/07/10/us/politics...,WASHINGTON — Several years of progress in redu...
20,0,,https://www.nytimes.com/2004/08/07/business/th...,"Stocks fell sharply yesterday, setting new low..."
21,0,"JAN. 27, 2009JAN. 27, 2009JAN. 28, 2009JAN. 27...",https://www.nytimes.com/2009/01/28/us/politics...,WASHINGTON — President Obama made a campaign t...
22,0,"Jan. 13, 2015",https://www.nytimes.com/2015/01/14/business/da...,Stocks swung from gains to losses and almost b...
23,0,"MARCH 2, 2007MARCH 2, 2007MARCH 2, 2007",https://www.nytimes.com/2007/03/02/business/02...,"WASHINGTON, March 1 — They are marketed as “in..."
24,0,"OCT. 24, 2004",https://www.nytimes.com/2004/10/24/business/yo...,IT'S often said that truth is the first casual...
25,0,"APRIL 20, 2008",https://www.nytimes.com/2008/04/20/magazine/20...,CHARGE THYSELF: When Freeplay’s windup radio c...
26,0,,https://www.nytimes.com/2001/10/04/us/nation-c...,President Bush urged Congress today to pass a ...
27,0,"May 20, 2015",https://www.nytimes.com/2015/05/21/us/obama-re...,"NEW LONDON, Conn. — President Obama used a com..."
28,0,"MAY 24, 2009",https://www.nytimes.com/2009/05/25/business/25...,"HOLIDAY WEEK Government offices, the markets a..."
29,0,,https://www.nytimes.com/video/us/politics/1248...,
...,...,...,...,...
1969,0,"SEPT. 6, 6800",https://www.nytimes.com/2001/09/27/business/a-...,The global economy is likely to grow at its we...
1970,0,"July 28, 2005 1:43 am",https://learning.blogs.nytimes.com/2005/07/28/...,Note: This lesson was originally published on ...
1971,0,,https://www.nytimes.com/2002/01/30/us/state-un...,Nearly a year after traveling to Capitol Hill ...
1972,0,"NOV. 18, 2010",https://www.nytimes.com/2010/11/19/opinion/l19...,"To the Editor:In “The Two Cultures” (column, N..."
1973,0,"June 7, 2018",https://www.nytimes.com/2018/06/07/opinion/tru...,"According to Alan Krueger and Eric Posner, in ..."
1974,0,"NOV. 4, 2008APRIL 21, 2011APRIL 21, 2011",https://www.nytimes.com/2008/11/05/business/05...,The Federal Reserve’s track record over its 95...
1975,0,"October 13, 2010 5:06 am",https://dealbook.nytimes.com/2010/10/13/jobs-a...,Wall Street is more worried about high unemplo...
1976,0,"June 17, 2016",https://www.nytimes.com/2016/06/19/upshot/one-...,"Economists, like physicians, sometimes confron..."
1977,0,,https://www.nytimes.com/2002/12/30/us/economic...,When Fred Hassan wanted to prove that Pharmaci...
1978,0,"FEB. 12, 2009FEB. 12, 2009FEB. 12, 2009",https://www.nytimes.com/2009/02/13/us/politics...,"EAST PEORIA, Ill. — President Obama brought hi..."
1979,0,"OCT. 30, 2015",https://www.nytimes.com/2015/11/01/upshot/is-t...,I write about economics for a living. Part of ...
1980,0,"Sept. 19, 2014",https://www.nytimes.com/2014/09/20/business/ho...,THE net worth of American households is now 20...
1981,0,"JUNE 17, 2008",https://www.nytimes.com/2008/06/17/books/17kak...,The title of Derek Chollet and James Goldgeier...
1982,0,,https://www.nytimes.com/2000/12/08/business/ne...,"The date was Aug. 21, 1990. The nation's last ..."
1983,0,,https://www.nytimes.com/2000/06/11/business/of...,"THE new economy is here, and its emblems have ..."
1984,0,"JAN. 8, 2011JAN. 8, 2011JAN. 8, 2011",https://www.nytimes.com/2011/01/09/business/09...,PHOENIX — An array of federal and state invest...
1985,0,"NOV. 6, 2006",https://query.nytimes.com/gst/fullpage.html?re...,"WASHINGTON CROSSING, Pa., Nov. 5 - Representat..."
1986,0,"APRIL 26, 2011",https://www.nytimes.com/2011/04/27/world/europ...,LONDON — It was dubbed the “He-cession.” As ma...
1987,0,"OCT. 25, 2008FEB. 22, 2015OCT. 25, 2008FEB. 22...",https://www.nytimes.com/2008/10/26/business/26...,As the financial crisis crimps demand for Amer...
1988,0,"FEB. 25, 2011",https://www.nytimes.com/2011/02/26/business/26...,Stocks rose Friday as oil prices stabilized af...
1989,0,"Oct. 15, 2015",https://www.nytimes.com/2015/10/16/us/politics...,WASHINGTON — The federal budget deficit fell t...
1990,0,,https://www.nytimes.com/2002/01/17/business/sc...,A roundup of regional economic conditions in r...
1991,0,,https://www.nytimes.com/2002/08/31/business/co...,Though the economy took a pummeling in the sec...
1992,0,"Sept. 4, 2014",https://www.nytimes.com/2014/09/05/business/ec...,WASHINGTON — Economic growth since the Great R...
1993,0,"May 6, 2014",https://www.nytimes.com/2014/05/07/business/us...,WASHINGTON — The United States trade deficit n...
1994,0,"JAN. 10, 2012",https://www.nytimes.com/2012/01/11/business/ec...,Wholesale businesses barely increased their st...
1995,0,"DEC. 7, 2008DEC. 7, 2008DEC. 7, 2008DEC. 7, 20...",https://www.nytimes.com/2008/12/08/washington/...,WASHINGTON — Congressional Democrats were draf...
1996,0,"JUNE 9, 2009FEB. 17, 2015FEB. 17, 2015",https://www.nytimes.com/2009/06/10/us/10charit...,Charitable giving fell last year by the larges...
1997,0,,https://www.nytimes.com/2002/08/22/business/ec...,"''PREDICTION is very difficult,'' Niels Bohr o..."
1998,0,"JUNE 3, 2011JUNE 3, 2011JUNE 3, 2011JUNE 3, 20...",https://www.nytimes.com/2011/06/04/business/ec...,"After several months of strong job growth, hir..."

In [127]:
text_dfs8_5001to7000_testing['url_date'] = text_dfs8_5001to7000_testing['url'].apply(regex_date)

In [128]:
text_dfs8_5001to7000_testing.head(3)

,index,date,url,article,url_date
0,0,"JUNE 21, 2006",https://www.nytimes.com/2006/06/21/business/21...,Wall Street pared an earlier advance to end mi...,2006-06-21
1,0,"Oct. 29, 2014",https://www.nytimes.com/2014/10/30/upshot/the-...,The most important thing to understand about t...,2014-10-30
2,0,"JULY 16, 2010MAY 11MAY 11MAY 4APR 27APR 16",https://www.nytimes.com/2010/07/17/your-money/...,"Sometime next week, President Obama will final...",2010-07-17

In [129]:
url_list7001to10000 = url_list[7001:10000]

In [130]:
text_dfs8_7001to10000 = [get_text1(url) for url in url_list7001to10000]

In [131]:
text_dfs8_7001to10000 = pd.concat(text_dfs8_7001to10000).reset_index()

In [132]:
text_dfs8_7001to10000.columns = ['index','date', 'url','article']

In [133]:
text_dfs8_7001to10000.head(2)

,index,date,url,article
0,0,"NOV. 1, 2006MARCH 9, 2015MARCH 9, 2015",https://www.nytimes.com/2006/11/01/business/01...,"A couple of years ago, Robert E. Rubin — émine..."
1,0,"OCT. 7, 2008",https://www.nytimes.com/2008/10/08/business/08...,DETROIT — The few consumers who are buying new...

In [134]:
pickle.dump( text_dfs8_7001to10000, open( "text_dfs8_7001to10000_testing", "wb" ) )

In [135]:
text_dfs8_7001to10000.shape

(2999, 4)

In [136]:
text_dfs8_7001to10000_testing = text_dfs8_7001to10000
text_dfs8_7001to10000_testing.dropna(subset = ['url','article'])

,index,date,url,article
0,0,"NOV. 1, 2006MARCH 9, 2015MARCH 9, 2015",https://www.nytimes.com/2006/11/01/business/01...,"A couple of years ago, Robert E. Rubin — émine..."
1,0,"OCT. 7, 2008",https://www.nytimes.com/2008/10/08/business/08...,DETROIT — The few consumers who are buying new...
2,0,,https://www.nytimes.com/2002/07/17/business/ma...,Prices of blue-chip stocks fell for the sevent...
3,0,"March 17, 2016March 17, 2016 6:06 am",https://news.blogs.nytimes.com/2016/03/17/morn...,ACKMAN CUTS HIS MONDELEZ STAKE | William A. ...
4,0,"Dec. 14, 2015",https://www.nytimes.com/2015/12/15/upshot/why-...,The Federal Reserve will most likely raise int...
5,0,,https://www.nytimes.com/2002/08/21/business/th...,The nation's trade deficit has narrowed slight...
6,0,"Oct. 3, 2016",https://www.nytimes.com/2016/10/04/upshot/dona...,"When you buy an “American-made” car, you are p..."
7,0,,https://www.nytimes.com/2000/10/02/opinion/l-p...,To the Editor:Re ''Forget Washington. The Poor...
8,0,"JUNE 17, 2009FEB. 17, 2015MAY 29MAY 22MAY 15MA...",https://www.nytimes.com/2009/06/17/business/ec...,Rationing.More to the point: Rationing!As in: ...
9,0,"Nov. 25, 2014",https://www.nytimes.com/2014/11/26/opinion/foo...,There are four basic ways to change the food s...
10,0,"APRIL 26, 2010",https://www.nytimes.com/2010/04/27/business/27...,"Realtors, home buyers and sellers are rushing ..."
11,0,,https://www.nytimes.com/2002/04/25/us/after-we...,The welfare rolls in seven Midwestern states s...
12,0,"SEPT. 9, 2010",https://www.nytimes.com/2010/09/10/opinion/10T...,WashingtonTHE trade figures from the Commerce ...
13,0,,https://www.nytimes.com/2003/12/05/opinion/l-k...,To the Editor:Although you criticize the Bush ...
14,0,"December 16, 2014 9:10 pm",https://dealbook.nytimes.com/2014/12/16/bond-i...,They were the darlings of global investors.Pet...
15,0,"AUG. 12, 2009",https://www.nytimes.com/2009/08/13/business/13...,Following is the text of the Federal Reserve’s...
16,0,"AUG. 8, 2011AUG. 7, 2011AUG. 8, 2011AUG. 7, 20...",https://www.nytimes.com/2011/08/09/opinion/the...,"THE Treasury can cry foul all it wants, but th..."
17,0,"APRIL 2, 2013",https://www.nytimes.com/2013/04/03/business/da...,"Stocks rose on Tuesday, led by the health care..."
18,0,,https://www.nytimes.com/2003/04/03/business/so...,While American optimism about the war in Iraq ...
19,0,"October 9, 2013 8:44 pm",https://dealbook.nytimes.com/2013/10/09/govern...,"In good times and bad, the worldâs financial..."
20,0,"January 20, 2010 4:54 am",https://dealbook.nytimes.com/2010/01/20/asia-t...,Japan Airlines isn’t the real prize in the fig...
21,0,,https://www.nytimes.com/2003/10/09/us/dean-say...,"Howard Dean, a candidate for the Democratic pr..."
22,0,"APRIL 13, 2012APRIL 13, 2012APRIL 13, 2012APRI...",https://www.nytimes.com/2012/04/15/sunday-revi...,"WASHINGTONON Jan. 1 of next year, the federal ..."
23,0,"JAN. 14, 2013JAN. 14, 2013JAN. 14, 2013",https://www.nytimes.com/2013/01/14/us/politics...,The following is the complete transcript of Pr...
24,0,"DEC. 18, 2011",https://www.nytimes.com/2011/12/19/opinion/don...,THE progressive reformer and eminent jurist Lo...
25,0,,https://www.nytimes.com/2005/12/05/business/bu...,"After 18 years in office, Alan Greenspan will ..."
26,0,"MAY 31, 2011MAY 31, 2011MAY 30, 2011MAY 31, 20...",https://www.nytimes.com/2011/06/01/business/01...,"How low can the market go?For real estate, som..."
27,0,"SEPT. 6, 1200",https://www.nytimes.com/2002/09/08/business/l-...,To the Editor:The theory that corporate cost-c...
28,0,"SEPT. 5, 2011",https://www.nytimes.com/2011/09/06/opinion/yes...,"Cambridge, Mass.ON Thursday, President Obama w..."
29,0,"May 11, 2015",https://www.nytimes.com/2015/05/11/opinion/pau...,Last year the vampires of finance bought thems...
...,...,...,...,...
2969,0,"JAN. 22, 2009SEPT. 22, 2008SEPT. 22, 2008",https://www.nytimes.com/2009/01/23/business/wo...,The Swedes have a simple message to the Americ...
2970,0,"AUG. 5, 2007AUG. 5, 2007AUG. 5, 2007",https://www.nytimes.com/2007/08/05/books/revie...,"Robert H. Frank, a professor of economics at C..."
2971,0,"Dec. 13, 2015",https://www.nytimes.com/2015/12/14/business/fe...,"On Tuesday, the Labor Department is expected t..."
2972,0,"SEPT. 6, 2000",https://www.nytimes.com/2003/03/24/business/th...,"With the battles having begun in Iraq, the Uni..."
2973,0,"APRIL 6, 2012APRIL 6, 2012APRIL 6, 2012APRIL 6...",https://www.nytimes.com/2012/04/07/business/ec...,WASHINGTON — When a lackluster jobs report cam...
2974,0,"MARCH 15, 2009MARCH 14, 2009MARCH 14, 2009",https://www.nytimes.com/2009/03/16/us/politics...,WASHINGTON — Top administration economic advis...
2975,0,"June 6, 2016June 6, 2016 5:59 am",https://news.blogs.nytimes.com/2016/06/06/morn...,CREDIT SUISSE BOSS FACES REVOLT | Credit Sui...
2976,0,"March 4, 2011 2:18 pm",https://economix.blogs.nytimes.com/2011/03/04/...,3:14 p.m. | Updated See note on break in the d...
2977,0,"MAY 13, 2011",https://www.nytimes.com/2011/05/13/technology/...,"Math majors, rejoice. Businesses are going to ..."
2978,0,,https://www.nytimes.com/2004/07/04/business/fu...,INVESTORS may not know how fast or how high ma...
2979,0,,https://learning.blogs.nytimes.com/2008/02/07/...,
2980,0,"APRIL 16, 2006",https://www.nytimes.com/2006/04/16/magazine/16...,"There are studies that prove it, but I don't n..."
2981,0,"Sept. 18, 2014",https://www.nytimes.com/2014/09/19/business/un...,The number of Americans filing new claims for ...
2982,0,"Nov. 5, 2014",https://www.nytimes.com/2014/11/06/upshot/wher...,Now that Republicans are set to control both h...
2983,0,"SEPT. 17, 2009",https://www.nytimes.com/2009/09/18/business/ec...,WASHINGTON (AP) — Americans’ wealth rose this ...
2984,0,,https://www.nytimes.com/2003/08/20/business/th...,DOLLAR DROPS. The dollar fell against the yen ...
2985,0,"FEB. 8, 2013",https://www.nytimes.com/2013/02/09/business/us...,The United States economy most likely expanded...
2986,0,"JAN. 7, 2011",https://www.nytimes.com/2011/01/08/business/ec...,"BERKELEY, Calif. — So how would he grade Pres..."
2987,0,"MAY 7, 2009MAY 7, 2009MAY 7, 2009MAY 6, 2009MA...",https://query.nytimes.com/gst/fullpage.html?re...,"Now that the stress tests are in, what do we r..."
2988,0,"SEPT. 21, 2010SEPT. 21, 2010MAY 29MAY 22MAY 15...",https://www.nytimes.com/2010/09/22/business/gl...,BeijingSpend enough time with Chinese official...
2989,0,"December 11, 2014 3:23 pm",https://op-talk.blogs.nytimes.com/2014/12/11/f...,
2990,0,"AUG. 28, 2013AUG. 28, 2013AUG. 28, 2013",https://www.nytimes.com/2013/08/29/business/ec...,MEMPHIS — Beneath the spreading shade tree in ...
2991,0,"MARCH 4, 2011MARCH 4, 2011OCT. 7, 2010MARCH 4,...",https://www.nytimes.com/2011/03/05/science/05l...,When five television studios became entangled ...
2992,0,"March 24, 2015",https://www.nytimes.com/2015/03/25/business/ri...,WASHINGTON — A modest rebound in gas costs and...
2993,0,"Dec. 13, 2017",https://www.nytimes.com/2017/12/13/business/fe...,The Federal Reserve’s decision to raise its be...
2994,0,,https://www.nytimes.com/interactive/2012/08/20...,
2995,0,"Feb. 10, 2014",https://www.nytimes.com/2014/02/11/opinion/bro...,When foreign visitors used to describe America...
2996,0,"DEC. 22, 2010",https://www.nytimes.com/2010/12/26/movies/26sc...,THE idea of the universal middle class is a pe...
2997,0,"Nov. 25, 2014",https://www.nytimes.com/2014/11/26/upshot/how-...,Many analysts were downright jubilant about a ...
2998,0,,https://www.nytimes.com/video/multimedia/10000...,

In [139]:
text_dfs8_7001to10000_testing.iloc[2998]

index                                                      0
date
url        https://www.nytimes.com/video/multimedia/10000...
article
Name: 2998, dtype: object

In [140]:
text_dfs8_7001to10000_testing['url_date'] = text_dfs8_7001to10000_testing['url'].apply(regex_date)

In [141]:
text_dfs8_7001to10000_testing.head()

,index,date,url,article,url_date
0,0,"NOV. 1, 2006MARCH 9, 2015MARCH 9, 2015",https://www.nytimes.com/2006/11/01/business/01...,"A couple of years ago, Robert E. Rubin — émine...",2006-11-01
1,0,"OCT. 7, 2008",https://www.nytimes.com/2008/10/08/business/08...,DETROIT — The few consumers who are buying new...,2008-10-08
2,0,,https://www.nytimes.com/2002/07/17/business/ma...,Prices of blue-chip stocks fell for the sevent...,2002-07-17
3,0,"March 17, 2016March 17, 2016 6:06 am",https://news.blogs.nytimes.com/2016/03/17/morn...,ACKMAN CUTS HIS MONDELEZ STAKE | William A. ...,2016-03-17
4,0,"Dec. 14, 2015",https://www.nytimes.com/2015/12/15/upshot/why-...,The Federal Reserve will most likely raise int...,2015-12-15

In [142]:
url_list10001to13000 = url_list[10001:13000]

In [143]:
text_dfs8_10001to13000 = [get_text1(url) for url in url_list10001to13000]

In [144]:
text_dfs8_10001to13000 = pd.concat(text_dfs8_10001to13000).reset_index()

In [145]:
text_dfs8_10001to13000.columns = ['index','date', 'url','article']

In [146]:
text_dfs8_10001to13000.shape

(2999, 4)

In [147]:
text_dfs8_10001to13000.head(4)

,index,date,url,article
0,0,"DEC. 15, 2012AUG 29AUG 19JUL 26JUL 24JUL 15",https://www.nytimes.com/2012/12/16/opinion/sun...,When President-elect Barack Obama selected Tim...
1,0,"OCT. 2, 2011",https://www.nytimes.com/2011/10/03/business/ec...,ECONOMIC REPORTS This week’s data will include...
2,0,"JUNE 13, 2013",https://www.nytimes.com/2013/06/14/business/da...,Good news about hiring and spending at retail ...
3,0,"May 21, 2015May 21, 2015 7:27 am",https://news.blogs.nytimes.com/2015/05/21/morn...,HEAVY FINES FOR FOREIGN EXCHANGE COLLUSION | ...

In [148]:
pickle.dump( text_dfs8_10001to13000, open( "text_dfs8_10001to13000_testing", "wb" ) )

In [150]:
text_dfs8_10001to13000_testing = text_dfs8_10001to13000

In [151]:
text_dfs8_10001to13000_testing['url_date'] = text_dfs8_10001to13000_testing['url'].apply(regex_date)

In [152]:
text_dfs8_10001to13000_testing.sample(10,random_state=42)

,index,date,url,article,url_date
1376,0,,https://www.nytimes.com/2000/10/14/business/pr...,American manufacturers were able to charge sur...,2000-10-14
932,0,"JUNE 11, 2010",https://www.nytimes.com/2010/06/12/business/12...,WASHINGTON — The Federal Reserve’s vice chairm...,2010-06-12
144,0,"April 6, 2015",https://www.nytimes.com/2015/04/07/business/ec...,WASHINGTON — Service companies in the United S...,2015-04-07
1752,0,"Aug. 11, 2016",https://www.nytimes.com/2016/08/12/us/politics...,"WARREN, Mich. — In a full-throttled rejection ...",2016-08-12
51,0,,https://www.nytimes.com/2003/09/07/business/on...,"ANOTHER Labor Day has passed, with the usual c...",2003-09-07
414,0,"Sept. 14, 2016",https://www.nytimes.com/2016/09/15/business/ec...,WASHINGTON — The eye-popping improvement in ec...,2016-09-15
2306,0,,https://www.nytimes.com/2003/09/17/business/fe...,The Federal Reserve retained its cautious outl...,2003-09-17
266,0,"FEB. 28, 2009",https://www.nytimes.com/2009/03/01/business/01...,"IN the world of technology, inventors are hail...",2009-03-01
2705,0,"Feb. 23, 2015",https://www.nytimes.com/2015/02/24/us/with-con...,WASHINGTON — President Obama on Monday moved t...,2015-02-24
2424,0,,https://www.nytimes.com/2001/09/17/business/af...,From the giant Ford Motor Company to the modes...,2001-09-17

In [159]:
url_list13001to14000 = url_list[13001:14000]

In [160]:
text_dfs8_13001to14000 = [get_text1(url) for url in url_list13001to14000]

In [161]:
text_dfs8_13001to14000 = pd.concat(text_dfs8_13001to14000).reset_index()

In [162]:
text_dfs8_13001to14000.columns = ['index','date', 'url','article']

In [164]:
text_dfs8_13001to14000.head(4)

,index,date,url,article
0,0,"JUNE 16, 2013",https://www.nytimes.com/2013/06/17/business/ec...,ECONOMIC REPORTS Data to be released this week...
1,0,"NOV. 23, 2009",https://www.nytimes.com/2009/11/23/us/politics...,President Obama’s scramble for a health care o...
2,0,"FEB. 13, 2009FEB. 13, 2009FEB. 13, 2009FEB. 13...",https://www.nytimes.com/2009/02/14/business/ec...,WASHINGTON — A provision buried deep inside th...
3,0,"NOV. 18, 2008",https://www.nytimes.com/2008/11/19/nyregion/19...,"Up and down Fifth Avenue, it is hard not to se..."

In [165]:
pickle.dump( text_dfs8_13001to14000, open( "text_dfs8_13001to14000_testing", "wb" ) )

In [166]:
text_dfs8_13001to14000_testing = text_dfs8_13001to14000

In [167]:
text_dfs8_13001to14000_testing['url_date'] = text_dfs8_13001to14000_testing['url'].apply(regex_date)

In [168]:
text_dfs8_13001to14000_testing.head(4)

,index,date,url,article,url_date
0,0,"JUNE 16, 2013",https://www.nytimes.com/2013/06/17/business/ec...,ECONOMIC REPORTS Data to be released this week...,2013-06-17
1,0,"NOV. 23, 2009",https://www.nytimes.com/2009/11/23/us/politics...,President Obama’s scramble for a health care o...,2009-11-23
2,0,"FEB. 13, 2009FEB. 13, 2009FEB. 13, 2009FEB. 13...",https://www.nytimes.com/2009/02/14/business/ec...,WASHINGTON — A provision buried deep inside th...,2009-02-14
3,0,"NOV. 18, 2008",https://www.nytimes.com/2008/11/19/nyregion/19...,"Up and down Fifth Avenue, it is hard not to se...",2008-11-19

In [170]:
text_dfs8_13001to14000_testing.shape

(999, 5)

In [171]:
url_list14001to15000 = url_list[14001:15000]

In [172]:
text_dfs8_14001to15000 = [get_text1(url) for url in url_list14001to15000]

In [173]:
text_dfs8_14001to15000 = pd.concat(text_dfs8_14001to15000).reset_index()

In [175]:
text_dfs8_14001to15000.columns = ['index','date', 'url','article']

In [176]:
text_dfs8_14001to15000.head(2)

,index,date,url,article
0,0,"JAN. 7, 2011",https://www.nytimes.com/2011/01/08/business/ec...,WASHINGTON — President Obama went to a busy wi...
1,0,"November 25, 2012 10:43 pm",https://economix.blogs.nytimes.com/2012/11/25/...,"Every year, the government spends more than $1..."

In [177]:
pickle.dump( text_dfs8_14001to15000, open( "text_dfs8_14001to15000_testing", "wb" ) )

In [178]:
text_dfs8_14001to15000_testing = text_dfs8_14001to15000

In [179]:
text_dfs8_14001to15000_testing['url_date'] = text_dfs8_14001to15000_testing['url'].apply(regex_date)

In [180]:
text_dfs8_14001to15000_testing.head(2)

,index,date,url,article,url_date
0,0,"JAN. 7, 2011",https://www.nytimes.com/2011/01/08/business/ec...,WASHINGTON — President Obama went to a busy wi...,2011-01-08
1,0,"November 25, 2012 10:43 pm",https://economix.blogs.nytimes.com/2012/11/25/...,"Every year, the government spends more than $1...",2012-11-25

In [183]:
url_list15001to16000 = url_list[15001:16000]

In [184]:
text_dfs8_15001to16000 = [get_text1(url) for url in url_list15001to16000]

In [185]:
text_dfs8_15001to16000 = pd.concat(text_dfs8_15001to16000).reset_index()

In [186]:
text_dfs8_15001to16000.columns = ['index','date', 'url','article']

In [187]:
pickle.dump( text_dfs8_15001to16000, open( "text_dfs8_15001to16000_testing", "wb" ) )

In [188]:
text_dfs8_15001to16000_testing = text_dfs8_15001to16000

In [189]:
text_dfs8_15001to16000_testing['url_date'] = text_dfs8_15001to16000_testing['url'].apply(regex_date)

In [190]:
text_dfs8_15001to16000_testing.head(2)

,index,date,url,article,url_date
0,0,"March 7, 2013 4:33 pm",https://query.nytimes.com/gst/fullpage.html?re...,9:00 p.m. | UpdatedFour years after the financ...,None
1,0,"January 28, 2014 11:00 am",https://economix.blogs.nytimes.com/2014/01/28/...,Phillip Swagel is a professor at the School of...,2014-01-28

In [191]:
df = pd.DataFrame()

def get_text2(url):
    try:
        stringone = ''
        content_string2 = ''
        content_string4 = ''
        string_date2 = ''
        string_date3 = ''
        page = requests.get(url).text
        soup = BeautifulSoup(page, "lxml")
        #url2 = pd.Series(url)

        article_content = soup.find_all('p', attrs={'class' : 'story-body-text story-content'})
            #print(article_content[0])
            #print(len(article_content))

        for i in article_content:
            stringone += i.text.strip()
        #print(stringone)
        article = pd.Series(stringone)

        if stringone == '':

            article_content1 = soup.find_all('p', attrs={'class' : 'css-1i0edl6 e2kc3sl0'})

            #string2 = '' ... moved to the top
            for i in article_content1:
                content_string2 += (i.text.strip())
            article = pd.Series(content_string2)

            if content_string2 == '':


                article_content_4 = soup.find_all('p', attrs={'class' : 'story-body-text'})
                #string4 = ''
                for i in article_content_4:
                    content_string4 += (i.text.strip())
                article = pd.Series(content_string4)



        date2 = soup.find_all('time', attrs={'class' : 'dateline'})
        #string_date2 = ''
        for i in date2:
            string_date2 += i.text.strip()
        df_date = pd.Series(string_date2) #to be appended to dataframe lower down

        if string_date2 == '':


            date3 = soup.find_all('time', attrs={'class' : 'css-pnci9c eqgapgq0'})
            #string_date3 = ''
            for i in date3:
                string_date3 += i.text.strip()
            df_date = pd.Series(string_date3)

            #if string_date3 == '':
                #masthead = soup.find_all(class_='sharetools theme-classic sharetools-masthead ')
                #a = str(masthead[0])
                #a = a.split("=")
                #a = [v.split("\" ")[0][1:] for v in a]
                #df_date = pd.Series(a[6])


        url2 = pd.Series(url) ##these are to be appended to dataframe lower down
        frames = [df_date,url2,article] #authorz,#descrip,
        result = pd.concat(frames,axis=1)

        return(result)
    
    except:
        return(None)

In [193]:
url_list16001to17000 = url_list[16001:17000]
text_dfs8_16001to17000 = [get_text2(url) for url in url_list16001to17000]

text_dfs8_16001to17000 = pd.concat(text_dfs8_16001to17000).reset_index()

In [195]:
text_dfs8_16001to17000.columns = ['index','date', 'url','article']

In [196]:
text_dfs8_16001to17000.shape

(998, 4)

In [197]:
text_dfs8_16001to17000.head(2)

,index,date,url,article
0,0,,https://www.nytimes.com/2002/01/12/business/wh...,Wholesale prices in the United States declined...
1,0,"FEB. 7, 2013",https://www.nytimes.com/2013/02/08/business/ec...,WASHINGTON (Reuters) — The number of Americans...

In [198]:
pickle.dump( text_dfs8_16001to17000, open( "text_dfs8_16001to17000_testing", "wb" ) )

In [209]:
text_dfs8_16001to17000_testing = text_dfs8_16001to17000

In [200]:
text_dfs8_16001to17000_testing['url_date'] = text_dfs8_16001to17000_testing['url'].apply(regex_date)

In [201]:
text_dfs8_16001to17000_testing.head(2)

,index,date,url,article,url_date
0,0,,https://www.nytimes.com/2002/01/12/business/wh...,Wholesale prices in the United States declined...,2002-01-12
1,0,"FEB. 7, 2013",https://www.nytimes.com/2013/02/08/business/ec...,WASHINGTON (Reuters) — The number of Americans...,2013-02-08

In [202]:
len(url_list)

19702

In [203]:
url_list17001to19702 = url_list[17001:19702]
text_dfs8_17001to19702 = [get_text2(url) for url in url_list17001to19702]

In [204]:
text_dfs8_17001to19702 = pd.concat(text_dfs8_17001to19702).reset_index()

In [205]:
text_dfs8_17001to19702.columns = ['index','date', 'url','article']

In [206]:
text_dfs8_17001to19702.shape

(2701, 4)

In [207]:
pickle.dump( text_dfs8_17001to19702, open( "text_dfs8_17001to19702_testing", "wb" ) )

In [210]:
text_dfs8_17001to19702_testing = text_dfs8_17001to19702

In [211]:
text_dfs8_17001to19702_testing['url_date'] = text_dfs8_17001to19702_testing['url'].apply(regex_date)

In [212]:
text_dfs8_17001to19702_testing.shape

(2701, 5)

## As described above, there now exist dataframes for ~19,000 articles. 

## Subsequent notebooks will replicate this process for the remaining articles in the corpus.